### ISSUE TITLE
图标适配反馈

### ISSUE THREAD

**Issue by moonbai** [fankes/MIUINativeNotifyIcon#10]
剪映 com.lemon.lv
钉钉 com.alibaba.android.rimet
贝壳找房 com.lianjia.beike

桌面图标截图:
![IMG_20220208_185346](https://user-images.githubusercontent.com/34854875/152973212-2efc5704-2c3e-4f65-8f48-b5cbe8bb3045.jpg)

**Comment by fankes** [comment]
1.36 fixed.
