### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by 347488418** [fankes/MIUINativeNotifyIcon#101]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 魔戒/com.pluto.mojie/#FFF8C50A

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 是VPN软件，下载链接https://down.mojie.xyz/Android_MoJie_1.0.4.04.apk

**Comment by fankes** [comment]
不适配 VPN，感谢

**Comment by 347488418** [comment]
> 不适配 VPN，感谢

那么能不能出个状态栏屏蔽app图标功能

**Comment by fankes** [comment]
> > 不适配 VPN，感谢
> 
> 那么能不能出个状态栏屏蔽app图标功能

没有这个功能，被 MIUI 砍了
