### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by li0625** [fankes/MIUINativeNotifyIcon#102]
**需要适配的 APP 名称/包名/通知图标颜色 **

* 央视新闻/cn.cntvnews/#ff071F69

* 

**提供相关 APP 的下载渠道截图以及简要说明用途 **

*酷安央视新闻APP下载页面 ![Screenshot_2022-08-23-19-03-52-332_com.coolapk.market.jpg](https://user-images.githubusercontent.com/104386128/186143667-6ddf32d9-6f33-47e9-b9ce-7a008d05e100.jpg)

**提供相关 APP 的通知单色图标适配素材 大小 50x50 **

* https://www.coolapk.com/apk/cn.cntvnews

*

**Comment by fankes** [comment]
@NekoMua

**Comment by NekoMua** [comment]
> @NekoMua

我人挂逼了，发烧到39℃多，明后天再说了😂

**Comment by li0625** [comment]
> > @NekoMua
> 
> 我人挂逼了，发烧到39℃多，明后天再说了😂
身体是革命的本钱 病好了再说
