### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by 1770438260** [fankes/MIUINativeNotifyIcon#103]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 海鸥加速器/tool.seagull.v/#FF1569CB

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 
![Screenshot_2022-08-27-01-05-47-965_com android vending](https://user-images.githubusercontent.com/63174937/186959900-2211d6b3-eedc-4f9c-bb5a-2bac5f52e841.jpg)
网络加速

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* 
![1661534587292](https://user-images.githubusercontent.com/63174937/186960165-1bf3f835-9215-473c-b176-c55232073e08.png)

*

**Comment by fankes** [comment]
不适配 VPN/翻墙 类 APP
