### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by LMS0513** [fankes/MIUINativeNotifyIcon#115]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

*Surf VPN/com.xfx.surfvpn/#1B9486

* 

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* ![Screenshot_2022-09-17-10-08-37-593_com.android.vending.jpg](https://user-images.githubusercontent.com/113742152/190836401-424ee028-9690-405f-9f02-4313830c32a2.jpg)

Surf VPN是专为移动设备设计的革命性VPN服务，可为世界各地的用户提供超快的速度和极其可靠的安全性。若想匿名并保护隐私，则Surf VPN是您最好的选择。

Surf VPN是专为移动设备设计的VPN服务，可为世界各地的用户提供超快的速度和极其可靠的安全性。若想匿名冲浪并保护隐私，则Surf VPN是您最好的选择。

**Comment by fankes** [comment]
不会适配 翻墙/VPN 等敏感 APP
