### ISSUE TITLE
图标适配反馈

### ISSUE THREAD

**Issue by moonbai** [fankes/MIUINativeNotifyIcon#12]
huazz145专用推送 com.huazz145push
番茄免费小说 com.dragon.read
顺序同图上顺序，感谢～
![Screenshot_2022-02-09-11-31-09-241_com miui securitycenter](https://user-images.githubusercontent.com/34854875/153117175-7a9a54b7-566c-4b98-b4cc-84ba26d98a8a.png)

**Comment by moonbai** [comment]
游戏高能时刻 com.xiaomi.migameservice
![Screenshot_2022-02-09-11-37-57-183_com miui securitycenter](https://user-images.githubusercontent.com/34854875/153117319-18a37583-b7ca-4ef2-b9fa-be52abf07551.jpg)

**Comment by lff1986** [comment]
风筝守护 com.kiteguard
![Uploading 357ed2b7b08908413c6513f7cdb71ae6.jpg…]()

**Comment by fankes** [comment]
> 风筝守护 com.kiteguard
> ![Uploading 357ed2b7b08908413c6513f7cdb71ae6.jpg…]()
> 

图没传成功

**Comment by moonbai** [comment]
王者营地 com.tencent.gamehelper.smoba
![Screenshot_2022-02-11-06-26-44-776_com miui home](https://user-images.githubusercontent.com/34854875/153507238-5801b6c5-8be7-4e58-8f75-e307f1281031.png)

**Comment by fankes** [comment]
适配完成
