### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by Sunwukong2** [fankes/MIUINativeNotifyIcon#120]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* (示例：Haylou Fun/com.yingsheng.hayloufun/#fff16033)

* 

**提供相关 APP 的下载渠道截图以及简要说明用途 (![Screenshot_2022-09-21-19-03-24-771_com.android.vending.jpg](https://user-images.githubusercontent.com/85972285/191488355-264ae451-4298-40de-8a0e-6581f2bf772e.jpg)哈喽智能手表搭配使用)**

* 

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by fankes** [comment]
@NekoMua

**Comment by fankes** [comment]
@NekoMua 漏了一个

**Comment by NekoMua** [comment]
> @NekoMua 漏了一个

我知道，还没做罢了
