### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by HundSimon** [fankes/MIUINativeNotifyIcon#126]
李跳跳

包名：cn.litiaotiao.app
版本名称：派大星2.01
版本代号：2

用于跳过开屏广告 常驻通知保活

https://wwe.lanzouw.com/iYBeL03thd3g?webpage=V2ZTMgxnVTUBYAJkBGRQZANvUGNWdQczCzRVZVU5Bj8HNgFjXTYHL1Uy
密码1233

这里就不提供图标内容了

**Comment by fankes** [comment]
因为一些原因，防止应用被下架，暂时不会适配李跳跳
