### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by Hehonge051** [fankes/MIUINativeNotifyIcon#128]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* KOOK语音/cn.kaiheila/#00FF00

*

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

＊来自小米应用商店       用于聊天社交
![Screenshot_2022-10-05-08-29-23-367_com.xiaomi.market.jpg](https://user-images.githubusercontent.com/110095079/193954911-22ab4a2f-71cd-44e6-aa03-a02bfcbf6905.jpg)

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**
＊无

**Comment by fankes** [comment]
@NekoMua

**Comment by fankes** [comment]
已适配
