### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by ganhuaizhong** [fankes/MIUINativeNotifyIcon#129]
### APP 名称

美团众包

### APP 包名

com.sankuai.meituan.dispatch.crowdsource

### 下载渠道、来源地址链接

酷安可以下载

### 简单描述适配的通知图标使用场景

打开会有后台正在运行的通知 有消息也会弹通知图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
