### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by qiubote** [fankes/MIUINativeNotifyIcon#131]
### APP 名称

美的家居

### APP 包名

com.midea.ai.appliances

### 下载渠道、来源地址链接

https://wwm.lanzouj.com/i793U0bq8gna

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
