### ISSUE TITLE
小爱翻译原生图标

### ISSUE THREAD

**Issue by Hehonge051** [fankes/MIUINativeNotifyIcon#132]
### APP 名称

小爱翻译

### APP 包名

com.xiaomi.aiasst.vision

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

下载时为应用彩色图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua 添加到 MIUI 目录
