### ISSUE TITLE
通知图标优化适配反馈

### ISSUE THREAD

**Issue by wangsicong163** [fankes/MIUINativeNotifyIcon#134]
### APP 名称

上海交通卡

### APP 包名

com.jiuyu.sptcc.cordova

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
