### ISSUE TITLE
LSPosed新版本已显示模块图标而不是调用系统的图标，可以不用优化了

### ISSUE THREAD

**Issue by Howard20181** [fankes/MIUINativeNotifyIcon#14]
![IMG_20220211_105628.jpg](https://user-images.githubusercontent.com/40033067/153531172-463b2dfe-589b-4bdf-9502-7c7fbcae8fff.jpg)

而且，MIUI原来的原生图标展开后是和标题应用颜色一致的，并不是完全黑的
![IMG_20220211_110119.jpg](https://user-images.githubusercontent.com/40033067/153531277-35fb9684-336a-4fa1-85b7-23999ba1f4d3.jpg)

**Comment by fankes** [comment]
好的，后面去掉

**Comment by fankes** [comment]
已去除并重新提交代码
