### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by zzzsycnm** [fankes/MIUINativeNotifyIcon#140]
### APP 名称

Battery Guru

### APP 包名

com.paget96.batteryguru

### 下载渠道、来源地址链接

https://wwn.lanzout.com/tp/iZqPt0d9pj2j password：3513

### 简单描述适配的通知图标使用场景

好像不会变色，就是一直挂在通知栏显示电流等信息的

### 通知单色图标适配素材 (大小 50x50~72x72)

![Battery Guru 原图](https://user-images.githubusercontent.com/35305647/198178343-bcb4294c-9d27-494d-85d5-8ff846d7d042.png)
![Battery Guru50x50](https://user-images.githubusercontent.com/35305647/198178359-da23956d-78e8-4f53-bda2-66f9b289e3b5.png)
![Battery Guru72x72](https://user-images.githubusercontent.com/35305647/198178368-5c0d0095-2a5d-40fe-ba64-a1a7c25a0932.png)
![Battery Guru50x50 无透明通道](https://user-images.githubusercontent.com/35305647/198178371-cd282eaa-2811-439c-937d-efaee60d4d1d.png)
![Battery Guru72x72 无透明通道](https://user-images.githubusercontent.com/35305647/198178377-61874f73-d62b-468e-907a-f5e9da44fd01.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
该应用没有图标适配问题，如果不会变色则为系统问题，如果是A13请更新到最新开发版
