### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by dcvh556tfg** [fankes/MIUINativeNotifyIcon#142]
### APP 名称

小福助手

### APP 包名

com.xiaofu.xf

### 下载渠道、来源地址链接

http://www.xiaofuapp.com:8001/invite?code=xiaofuproxy3

### 简单描述适配的通知图标使用场景

VPN，免费的，求适配

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
视力不佳时您可在提交适配前换一副眼镜
