### ISSUE TITLE
请求适配爱发电

### ISSUE THREAD

**Issue by Hehonge051** [fankes/MIUINativeNotifyIcon#143]
### APP 名称

爱发电

### APP 包名

net.afdian.afdian

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

Mi Push推送以及应用自身推送均为彩色

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
