### ISSUE TITLE
图标适配反馈

### ISSUE THREAD

**Issue by billqiao1991** [fankes/MIUINativeNotifyIcon#15]
![同花顺](https://user-images.githubusercontent.com/99520645/153694344-22ac17d8-beb6-4534-9f4c-dfcbf3b54ff3.jpg)
![新浪财经](https://user-images.githubusercontent.com/99520645/153694345-5ba5b4fa-bcf7-4dbd-8178-04b563afc2fc.jpg)
![雪球](https://user-images.githubusercontent.com/99520645/153694349-2fb521ab-7e1a-4535-bca4-b26d63b7287c.jpg)
求增加同花顺、新浪财经和雪球的图标适配

**Comment by fankes** [comment]
请将包名用文字写上，不要截图谢谢！

**Comment by billqiao1991** [comment]
不好意思
同花顺 com.hexin.plat.android
新浪财经 cn.com.sina.finance
雪球 com.xueqiu.android

**Comment by fankes** [comment]
适配完成
