### ISSUE TITLE
【图标适配反馈】

### ISSUE THREAD

**Issue by Danehy** [fankes/MIUINativeNotifyIcon#151]
### APP 名称

转转

### APP 包名

com.wuba.zhuanzhuan

### 下载渠道、来源地址链接

https://app.xiaomi.com/details?id=com.wuba.zhuanzhuan

### 简单描述适配的通知图标使用场景

小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

![com wuba zhuanzhuan](https://user-images.githubusercontent.com/70059256/202879410-9c2eb7b4-15be-45fa-aee3-09aa4b345060.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
