### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by Spturate** [fankes/MIUINativeNotifyIcon#156]
### APP 名称

MissLee

### APP 包名

cn.litiaotiao.app

### 下载渠道、来源地址链接

微信公众号：李跳跳大小姐

### 简单描述适配的通知图标使用场景

通知栏会显示出应用图标有点突兀

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
https://github.com/fankes/MIUINativeNotifyIcon/files/8147189/Miui.12.Notification.Importance_1.2.zip

**Comment by fankes** [comment]
https://github.com/fankes/MIUINativeNotifyIcon/files/8147189/Miui.12.Notification.Importance_1.2.zip

**Comment by fankes** [comment]
下载 [这个模块](https://github.com/fankes/MIUINativeNotifyIcon/files/8147189/Miui.12.Notification.Importance_1.2.zip) 然后激活，然后长按李跳跳的通知，进入通知渠道中，将优先级设置为最小化，即可隐藏状态栏上的图标，李跳跳的图标没有人画，没有合适的图标且它不应该显示，所以不能适配。
