### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by zweidyx** [fankes/MIUINativeNotifyIcon#159]
### APP 名称

天书

### APP 包名

com.ss.android.lark.kazdtq

### 下载渠道、来源地址链接

https://packdownload.cttq.com/download/install.html

### 简单描述适配的通知图标使用场景

有消息时会出现图标通知

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
