### ISSUE TITLE
图标适配反馈

### ISSUE THREAD

**Issue by Qi-yuxuan** [fankes/MIUINativeNotifyIcon#16]
企业微信 com.tencent.wework
消息接收 top.tdtt.news

**Comment by Qi-yuxuan** [comment]
![IMG_20220212_174619](https://user-images.githubusercontent.com/62003656/153706271-fd812b3e-6f79-4d93-9992-8f8b07d862ee.jpg)

**Comment by fankes** [comment]
请告诉我“消息接收”是个啥

**Comment by Qi-yuxuan** [comment]
emmm用备用机来转发一些不支持mipush的app的消息……

**Comment by fankes** [comment]
适配完成
