### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by Readanyview** [fankes/MIUINativeNotifyIcon#163]
### APP 名称

阿里邮箱

### APP 包名

com.alibaba.cloudmail

### 下载渠道、来源地址链接

https://download.alicdn.com/wireless/alimei-android-outside/release/cloudmail.apk

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
