### ISSUE TITLE
请求适配DJI Fly

### ISSUE THREAD

**Issue by Hehonge051** [fankes/MIUINativeNotifyIcon#164]
### APP 名称

DJI Fly

### APP 包名

dji.go.v5

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

mipush推送以及自身都是彩色

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
