### ISSUE TITLE
请求适配阳光惠生活

### ISSUE THREAD

**Issue by Hehonge051** [fankes/MIUINativeNotifyIcon#165]
### APP 名称

阳光惠生活

### APP 包名

com.ebank.creditcard

### 下载渠道、来源地址链接

酷安

### 简单描述适配的通知图标使用场景

app推送消息都为彩色图标

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
