### ISSUE TITLE
请求适配腾讯会议通知栏图标

### ISSUE THREAD

**Issue by zweidyx** [fankes/MIUINativeNotifyIcon#17]
![Screenshot_2022-02-13-01-59-27-091_com tencent wemeet app](https://user-images.githubusercontent.com/4342148/153722655-e4fc434d-e36d-4d16-8400-8b39718b6c07.jpg)

**Comment by zweidyx** [comment]
腾讯会议com.tencent.wemeet.app

**Comment by fankes** [comment]
适配完成
