### ISSUE TITLE
[问题与 BUG 反馈] (从2.9版本开始会偶发导致系统界面崩溃重启)

### ISSUE THREAD

**Issue by Leungsiuyin** [fankes/MIUINativeNotifyIcon#173]
### 模块版本

2.9与2.95

### MIUI 版本

13.0.6

### MIUI 版本类型

稳定版

### Android 版本

12

### Xposed 框架名称与版本号

LSPosed1.8.6(6712)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

无

### 详细描述问题发生的具体原因

手机型号是红米k30pro 变焦版

2.8的时候都没有这个情况

从2.9开始，包括最新的2.95，都会偶尔出现系统界面崩溃重启，需要重新点亮屏幕输入密码进系统的情况
曾经出现在：
1.打王者的时候
2.导航的时候
3.看小说的时候

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

不知道应该如何抓log，愿意配合抓取。

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
我也出现了，但是无法定位问题，后面再找找解决方案。

**Comment by Leungsiuyin** [comment]
辛苦作者大大。有什么需要配合调试，抓log的可以跟我说。我目前是退回2.8用的

**Comment by fankes** [comment]
问题应该是解决了，如果更新版本后还未解决，请重新打开此问题

**Comment by Zxilly** [comment]
该问题仍然存在

**Comment by Art-Chen** [comment]
同碰到了OOM 抓了hprof分析 发现是这个模块导致的。
看起来是Method Cache导致的，有一个HashMap<Int, HashSet<>>占用了200多M的Heap，挑选了一些来看 都是一些Method在里面 怀疑是YukiHookApi问题？如果需要hprof文件的话可以提供，版本是2.95，目前更新2.98看看问题还有没有。
![image](https://user-images.githubusercontent.com/6419672/233632216-076bbe80-0d0a-4b7e-a292-97600d202029.png)

**Comment by fankes** [comment]
昨天晚上就修了，缓存换到 LruCache，如果依然 OOM，可以手动把缓存功能关掉

**Comment by fankes** [comment]
已修复，感谢 @Art-Chen
