### ISSUE TITLE
网易云音乐播放时通知图标显白

### ISSUE THREAD

**Issue by axelpln** [fankes/MIUINativeNotifyIcon#177]
### 模块版本

2.95

### MIUI 版本

14.0.3

### MIUI 版本类型

稳定版

### Android 版本

12

### Xposed 框架名称与版本号

LSPosed 1.8.6(6712)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

无

### 详细描述问题发生的具体原因

网易云音乐的通知图标只有白色，这导致系统为显示白色等亮色背景而将通知图标显示为暗色时，网易云音乐的图标依然为白色。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
这是 MIUI 的问题，请把网易云音乐的通知栏调整为系统样式就没有图标了，这种问题不再做回复，也不能修复
