### ISSUE TITLE
[待讨论] 原生图标相关适配问题

### ISSUE THREAD

**Issue by Howard20181** [fankes/MIUINativeNotifyIcon#18]
原生图标是有颜色的，并不是完全黑的。MIUI的原生图标也是支持的
![IMG_20220215_224927.jpg](https://user-images.githubusercontent.com/40033067/154086789-bdc5e60f-5f5e-4ee1-81c2-8736dd1f6f5a.jpg) 

可以禁用本模块，看看 https://github.com/lamprose/miultra 打开的MIUI原生图标

**Comment by fankes** [comment]
非常感谢，是我忽略了图标颜色的问题，这个问题将在稍后重新发布版本进行修复

**Comment by fankes** [comment]
该问题已修复

**Comment by Howard20181** [comment]
感谢修复
但是还是发现一个不规范的影响不大的小问题，在低优先级可以折叠成一行的通知收起来是会变黑白的，展开才彩色，本模块不会有这个效果。如果不追求与原生完全一致这个可以忽略
效果如视频
https://user-images.githubusercontent.com/40033067/154181279-c8a75619-fa80-4832-8710-1ebfaffac04c.mp4

**Comment by fankes** [comment]
> 感谢修复
> 但是还是发现一个不规范的影响不大的小问题，在低优先级可以折叠成一行的通知收起来是会变黑白的，展开才彩色，本模块不会有这个效果。如果不追求与原生完全一致这个可以忽略
> 效果如视频
> https://user-images.githubusercontent.com/40033067/154181279-c8a75619-fa80-4832-8710-1ebfaffac04c.mp4

这个特性是 Android 12 之前的，之后完全修改了，不是很想适配之前的版本了，主要是感觉没必要了，通知展开折叠的情况也是需要判断的，MIUI 改的太乱了，如果你能接受就这样吧，有问题可以后期再说。

**Comment by Howard20181** [comment]
发现一个问题，折叠后通知刷新图标颜色会闪，看起来是黑白被设置成彩色https://user-images.githubusercontent.com/40033067/154276897-e83e1afc-d052-43cd-ab0b-a4999d4182d2.mp4

**Comment by fankes** [comment]
> 发现一个问题，折叠后通知刷新图标颜色会闪，看起来是黑白被设置成彩色
> 
> https://user-images.githubusercontent.com/40033067/154276897-e83e1afc-d052-43cd-ab0b-a4999d4182d2.mp4

裂开，我真的不想适配旧版本了，那就有时间修一下吧

**Comment by fankes** [comment]
该问题被设置为待讨论状态，如果其他人有相同建议可在下方继续评论

**Comment by fankes** [comment]
使用相同的版本无法实现可折叠的效果，请问你使用的 Clash 版本是多少呢，最新版本已经没有折叠功能了，而且也没发现通知被折叠的可能性

**Comment by Howard20181** [comment]
> 使用相同的版本无法实现可折叠的效果，请问你使用的 Clash 版本是多少呢，最新版本已经没有折叠功能了，而且也没发现通知被折叠的可能性

低优先级的通知会被折叠，虽然MIUI上没有设置，但是这个流量通知好像默认就是低优先级的 

单个通知通道的重要程度设置在MIUI上被隐藏了，图示如下

![Screenshot_2022-02-27-02-10-06-912_com.android.settings.jpg](https://user-images.githubusercontent.com/40033067/155854362-b6def9ab-5af2-4599-aafd-7340fcf70b94.jpg)

可以使用这个Xposed模块加回设置入口
![IMG_20220227_021352.jpg](https://user-images.githubusercontent.com/40033067/155854461-09f7bc94-8627-4664-9bb1-057757725b51.jpg)

**Comment by naicfeng** [comment]
复现条件比较苛刻，可作为低优先级TODO
首选建议迁移到 Android 12 ，折叠无问题

https://user-images.githubusercontent.com/18218380/155855675-e62ebe9c-0bb8-42ad-ae11-4fc43062687e.mp4

**Comment by Howard20181** [comment]
> 复现条件比较苛刻，可作为低优先级TODO
> 首选建议迁移到 Android 12 ，折叠无问题
> 
> https://user-images.githubusercontent.com/18218380/155855675-e62ebe9c-0bb8-42ad-ae11-4fc43062687e.mp4
> 
> 

这个是原生样式的通知？
可惜小米9已经没有官方的Android 12了，除非抛弃MIUI否则用不上｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡

**Comment by naicfeng** [comment]
> 虽然兼容了原生图标颜色，但因为Material You的出现，个人更喜欢所有图标共用一套系统主题色。能否做到能开关通知图标颜色？

符合规范的APP可以自行决定图标是否上色

**Comment by naicfeng** [comment]
> > 虽然兼容了原生图标颜色，但因为Material You的出现，个人更喜欢所有图标共用一套系统主题色。能否做到能开关通知图标颜色？
> 
> 原生是怎么处理的？我建议与原生的行为保持一致

这个就是miui13(a12)开原生通知的样式。
原生的行为是，如果应用没有给图标指定颜色(是透明)，就系统指定一个(图标内容是白，上色在背景)。图标指定自己为什么颜色背景就会上什么颜色。图标指定自己为彩色就是彩色

**Comment by Agoines** [comment]
> > 发现一个问题，折叠后通知刷新图标颜色会闪，看起来是黑白被设置成彩色
> > 
> > https://user-images.githubusercontent.com/40033067/154276897-e83e1afc-d052-43cd-ab0b-a4999d4182d2.mp4
> 
> 裂开，我真的不想适配旧版本了，那就有时间修一下吧

在 Android 12 也有类似问题，在通知被刷新的时候会闪烁一下。

**Comment by fankes** [comment]
> > > 发现一个问题，折叠后通知刷新图标颜色会闪，看起来是黑白被设置成彩色
> > > 
> > > https://user-images.githubusercontent.com/40033067/154276897-e83e1afc-d052-43cd-ab0b-a4999d4182d2.mp4
> > 
> > 裂开，我真的不想适配旧版本了，那就有时间修一下吧
> 
> 在 Android 12 也有类似问题，在通知被刷新的时候会闪烁一下。

这个已经在说明里写明，是 MIUI 自己的问题，您不看说明的吗

**Comment by fankes** [comment]
> 虽然兼容了原生图标颜色，但因为Material You的出现，个人更喜欢所有图标共用一套系统主题色。能否做到能开关通知图标颜色？

是可以做到，但是这不符合原生规范，破坏了应用自有通知图标颜色，就像 MIUI 的屎山一样，这不是这个模块要做的事情

**Comment by YifePlayte** [comment]
> 

嗯，理解

**Comment by YifePlayte** [comment]
> > 虽然兼容了原生图标颜色，但因为Material You的出现，个人更喜欢所有图标共用一套系统主题色。能否做到能开关通知图标颜色？
> 
> 是可以做到，但是这不符合原生规范，破坏了应用自有通知图标颜色，就像 MIUI 的屎山一样，这不是这个模块要做的事情

好的，理解。

**Comment by fankes** [comment]
该问题在最新版本已被修复，请核实并更新即可
