### ISSUE TITLE
图标异常

### ISSUE THREAD

**Issue by Origin0915** [fankes/MIUINativeNotifyIcon#183]
### APP 名称

网易云音乐

### APP 包名

com.netease.cloudmusic

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

![Screenshot_2023-07-21-10-32-12-284_com fankes miui notify](https://github.com/fankes/MIUINativeNotifyIcon/assets/79388003/dad9b119-be0d-422f-b9de-8e51e9d4803b)
网易云音乐，消息通知显示正常，但是播放歌曲的时候，常驻状态栏那个播放器图标不正常

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
已重复强调这个问题是 MIUI 的问题，请在网易云音乐里把通知栏调整系统样式，就没有图标了

**Comment by fankes** [comment]
问题提交格式错误，将被关直接关闭

**Comment by fankes** [comment]
Duplicate at #117

**Comment by Origin0915** [comment]
好的
