### ISSUE TITLE
通知图标样式有时会出问题

### ISSUE THREAD

**Issue by Thomitics** [fankes/MIUINativeNotifyIcon#184]
图标样式变成类似于一个圆环套住一个方形图标，很难看，希望能修复一下
![Screenshot_2023-07-27-17-15-16-211_com fankes miu](https://github.com/fankes/AndroidNotifyIconAdapt/assets/62173814/ec4f55c9-b379-40f9-b648-7cb6a4e21b2a)

**Comment by Thomitics** [comment]
> 你是否使用了其它通知图标模块或者使用了第三方小米推送模块，如果是那么无法修复

使用了，不过今天我经过一些尝试之后发现了一个解决方案，只要这种出问题的应用启用“全部替换”就不会有问题了，但不知道会不会有什么副作用

**Comment by Thomitics** [comment]
也希望后续能加入一个“全部启用全部替换”的功能

**Comment by fankes** [comment]
> 也希望后续能加入一个“全部启用全部替换”的功能

我们不能破坏遵守规范的图标，你这样等于破坏所有遵守规范的图标，所以这个功能不会存在，因为我们的目的是规范，而不是破坏

**Comment by fankes** [comment]
> > 你是否使用了其它通知图标模块或者使用了第三方小米推送模块，如果是那么无法修复
> 
> 使用了，不过今天我经过一些尝试之后发现了一个解决方案，只要这种出问题的应用启用“全部替换”就不会有问题了，但不知道会不会有什么副作用

副作用就是破坏应用自身的图标达到修复的目的，这个图标是你第三方框架提供的，被识别为单色图标就会使用它提供的图标，默认智只会替换彩色图标

**Comment by fankes** [comment]
该问题的讨论已结束，与模块无关，愿意使用第三方框架的请找第三方框架开发者，而不是我们，这不是我们的 bug 也不由我们来修复。
