### ISSUE TITLE
[问题与 BUG 反馈] (Android 14失效，所有通知图标显示为灰色方块)

### ISSUE THREAD

**Issue by hmy65** [fankes/MIUINativeNotifyIcon#186]
### 模块版本

2.101 最新的action版本

### MIUI 版本

14.0.23.8.15.DEV（Android14 版本 底下的选不了14）

### MIUI 版本类型

开发版

### Android 版本

13

### Xposed 框架名称与版本号

1.8.6（6983）

### 与系统界面(系统 UI)同作用域的 Xposed 模块

Cemiuiler

### 详细描述问题发生的具体原因

正常激活，所有通知图标显示为灰色方块

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

无

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
NO LOG NO SCREENSHORT NO FIX
THANKS

**Comment by hmy65** [comment]
吃火药了？
