### ISSUE TITLE
[问题与 BUG 反馈] MIUI14 Android 14 表现异常

### ISSUE THREAD

**Issue by naicfeng** [fankes/MIUINativeNotifyIcon#189]
### 模块版本

2.101 ci f1fd3f2

### MIUI 版本

V14.0.3.0.UMCCNXM

### MIUI 版本类型

稳定版

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed 1.9.1 

### 与系统界面(系统 UI)同作用域的 Xposed 模块

无

### 详细描述问题发生的具体原因

状态栏，未下拉，显示纯色图标。下拉显示图标正常，日志为 release 版导出。

debug 版本不知为何无法激活，表现为在lsposed管理器内激活无反应，按钮状态也不变成已勾选

### 提供模块问题 Log 或必要 Log

There was an error creating your issue: body is too long (maximum is 65536 characters).

将在下面上传附件

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by naicfeng** [comment]
[miui_notification_icons_processing_logs.log](https://github.com/fankes/MIUINativeNotifyIcon/files/12837959/miui_notification_icons_processing_logs.log)

**Comment by naicfeng** [comment]
![Screenshot_2023-10-07-21-31-18-500_com fankes miui notify](https://github.com/fankes/MIUINativeNotifyIcon/assets/18218380/2e2d4e6c-5ea9-421f-b127-eaaa8dd6b448)
![Screenshot_2023-10-07-21-31-40-716_com fankes miui notify](https://github.com/fankes/MIUINativeNotifyIcon/assets/18218380/febd26b1-3c34-46ac-b6a7-528472af2201)

**Comment by fankes** [comment]
是的，但是我没有 MIUI 14 on Android 14 的设备，所以无法动态调试，你可以提供 MiuiSystemUI.apk 我可以暂时看看

**Comment by naicfeng** [comment]
[MiuiSystemUI_20230316.0.zip](https://github.com/fankes/MIUINativeNotifyIcon/files/12837973/MiuiSystemUI_20230316.0.zip)

MiuiSystemUI

**Comment by fankes** [comment]
看了一下，改动非常巨大，没系统怕是不能调试了，估计要一段时间了

**Comment by fankes** [comment]
新版本已修复完毕。
