### ISSUE TITLE
图标适配反馈

### ISSUE THREAD

**Issue by scrpr** [fankes/MIUINativeNotifyIcon#19]
「AcFun」`tv.acfundanmaku.video`
「今日校园」`com.wisedu.cpdaily`
「中国银行」`com.chinamworld.bocmbci`
![AcFun](https://user-images.githubusercontent.com/46473171/154107387-effa09d3-62fb-4d0d-8941-7645b67fef02.png) ![今日校园](https://user-images.githubusercontent.com/46473171/154107695-4b497ccc-c7d3-4cff-a1f4-3c8484287f70.png) ![中国银行](https://user-images.githubusercontent.com/46473171/154107713-c9c74ace-c2c1-4ad4-845f-e74f3fedfba0.png)
自制3枚图标供参考，迫于不会Android开发不能自己提pr，只能来开个issue了
[tv.acfundanmaku.video_xxxdpi](https://user-images.githubusercontent.com/46473171/154115288-4153d63f-a505-4d98-b3ca-a487dbbe9cfc.png)
[com.wisedu.cpdaily_xxxdpi](https://user-images.githubusercontent.com/46473171/154115311-512c502d-cd9d-45ef-b2a5-ed5588662f54.png)
[com.chinamworld.bocmbci_xxxdpi](https://user-images.githubusercontent.com/46473171/154115324-1faae608-82da-4b98-9ca8-676d450a630e.png)

**Comment by fankes** [comment]
...图标太大了，我给你改小吧

**Comment by scrpr** [comment]
不知道大小应该是多少所以按照xxxhdpi做的，看到之前issue里面原神的icon也是96px还以为没问题呢😥

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fankes** [comment]
已适配
