### ISSUE TITLE
[问题与 BUG 反馈] HyperOS 上导致“不显示通知图标”功能失效

### ISSUE THREAD

**Issue by Robotxm** [fankes/MIUINativeNotifyIcon#195]
### 模块版本

2.110

### 系统版本

HyperOS 1.0.23.11.8 DEV

### 系统版本类型

开发内测版

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed 1.9.2(7024)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

无

### 详细描述问题发生的具体原因

即使在系统设置里“通知和状态栏”关闭了“显示通知图标”，当启用此模块时，来新的通知的时候也会在状态栏显示通知图标。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

----part 1 start----
[ 2023-11-16T22:55:03.127     1001:  5665:  5665 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:03.191     1001:  5665:  5665 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:03.259     1000:  5683:  5683 I/LSPosed-Bridge  ] Loading legacy module com.fankes.miui.notify from /data/app/~~3G793y2Z6Av4CvrVy7u0bw==/com.fankes.miui.notify-wbcr4JqFybyDhMe4cm5IBA==/base.apk
[ 2023-11-16T22:55:03.271     1000:  5683:  5683 I/LSPosed-Bridge  ]   Loading class com.fankes.miui.notify.hook.HookEntry_YukiHookXposedInit
[ 2023-11-16T22:55:03.437     1001:  5665:  5665 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:34  当前版本名：14
[ 2023-11-16T22:55:03.439     1001:  5665:  5665 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:短信  当前版本号:34  当前版本名：14
[ 2023-11-16T22:55:03.440     1001:  5665:  5665 I/LSPosed-Bridge  ] Ankio-短信 -> Hooking dispatchIntent() for Android v29+
[ 2023-11-16T22:55:09.474    10134:  8609:  8609 I/LSPosed-Bridge  ] Loading legacy module com.moefactory.bettermiuiexpress from /data/app/~~DsAH-EDGThJuJ7hGaUXhYQ==/com.moefactory.bettermiuiexpress-C0tpVf4xtGoOhWWv3xp1ng==/base.apk
[ 2023-11-16T22:55:09.500    10134:  8609:  8609 I/LSPosed-Bridge  ]   Loading class com.moefactory.bettermiuiexpress.hook.HookEntry_YukiHookXposedInit
[ 2023-11-16T22:55:09.692    10134:  8609:  8810 I/LSPosed-Bridge  ] [BetterMiuiExpress][E][com.miui.personalassistant]--> HookClass [VariousClass] not found
[ 2023-11-16T22:55:09.693    10134:  8609:  8810 E/LSPosed-Bridge  ] java.lang.Throwable: VariousClass match failed of those ["com.miui.personalassistant.service.express.ExpressIntentUtils","com.miui.personalassistant.express.ExpressIntentUtils"]
	at w2.b.a(SourceFile:56)
	at com.moefactory.bettermiuiexpress.hook.HookEntry$onHook$1.i(SourceFile:229)
	at com.moefactory.bettermiuiexpress.hook.b.a(SourceFile:417)
	at com.moefactory.bettermiuiexpress.hook.HookEntry_YukiHookXposedInit.handleLoadPackage(SourceFile:12)
	at PftiBShrJI.rarcBYg.GEE.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at PftiBShrJI.rarcBYg.GEE.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at PftiBShrJI.rarcBYg.GEE.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:281)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1141)
	at android.app.LoadedApk.getResources(LoadedApk.java:1400)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3335)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3327)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7334)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2375)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
[ 2023-11-16T22:55:10.153    10187:  9069:  9069 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:10.550    10187:  9069:  9069 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:10.820    10187:  9069:  9069 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:70000001  当前版本名：7.0.1-C
[ 2023-11-16T22:55:11.491    10187:  9814:  9814 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:11.877    10187:  9814:  9814 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:12.245    10187:  9814:  9814 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:70000001  当前版本名：7.0.1-C
[ 2023-11-16T22:55:14.748    10402: 11171: 11171 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:15.062    10402: 11171: 11171 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:15.674    10402: 11171: 11171 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:921  当前版本名：10.5.36.8100
[ 2023-11-16T22:55:15.675    10402: 11171: 11171 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:支付宝  当前版本号:921  当前版本名：10.5.36.8100
[ 2023-11-16T22:55:17.977    10402: 12190: 12190 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:18.070    10402: 12190: 12190 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:18.313    10402: 12190: 12190 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:921  当前版本名：10.5.36.8100
[ 2023-11-16T22:55:19.740    10161: 12757: 12757 I/LSPosed-Bridge  ] Loading legacy module com.rong862.SplashAd from /data/app/~~cdTeF3196byGUtxuxe2crA==/com.rong862.SplashAd-nk6EWCTJXzfrGM6XL7YjPA==/base.apk
[ 2023-11-16T22:55:19.742    10161: 12757: 12757 I/LSPosed-Bridge  ]   Loading class com.rong862.SplashAd.MainHook
[ 2023-11-16T22:55:19.920    10161: 12757: 12757 I/LSPosed-Bridge  ] 【开屏小能手】【LoadPackage】com.xiaomi.market is loading ! !
[ 2023-11-16T22:55:20.595    10254: 12981: 12981 I/LSPosed-Bridge  ] Loading legacy module com.fkzhang.wechatxposed from /data/app/~~DP7kFeaA2PJsb201nKAsLA==/com.fkzhang.wechatxposed-xqIfTOTt-bVyJEMXwFd0yg==/base.apk
[ 2023-11-16T22:55:20.628    10254: 12981: 12981 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-11-16T22:55:20.629    10254: 12981: 12981 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:20.907    10254: 12981: 12981 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:20.916    10254: 12981: 12981 I/LSPosed-Bridge  ] Loading legacy module me.kyuubiran.qqcleaner from /data/app/~~Ia7uSU6swfmGncqVS3RQrw==/me.kyuubiran.qqcleaner-BTWrRr-Dh8rSaoLvqao5Rw==/base.apk
[ 2023-11-16T22:55:20.941    10254: 12981: 12981 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-11-16T22:55:20.998    10254: 12981: 12981 I/LSPosed-Bridge  ] Loading legacy module com.fankes.tsbattery from /data/app/~~kJatdKk1RMgWDXHwAslHwQ==/com.fankes.tsbattery-M-WqgBWspMtM-GNTt7d8DQ==/base.apk
[ 2023-11-16T22:55:21.115    10254: 12981: 12981 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-11-16T22:55:21.256    10402: 13258: 13258 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:21.351    10402: 13258: 13258 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:21.931    10402: 13258: 13258 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:921  当前版本名：10.5.36.8100
[ 2023-11-16T22:55:25.123    10254: 12981: 12981 I/LSPosed-Bridge  ] WeXposed: init context hook
[ 2023-11-16T22:55:25.166    10254: 12981: 12981 I/LSPosed-Bridge  ] WeXposed: loading WeXposed com.fkzhang.wechatxposed 2.42 (109) Lsposed
[ 2023-11-16T22:55:25.166    10254: 12981: 12981 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm:push Wechat version 8.0.31 (2280)
[ 2023-11-16T22:55:25.166    10254: 12981: 12981 I/LSPosed-Bridge  ] WeXposed: Xiaomi 2304FPN6DC Android 14 (34) arm64
[ 2023-11-16T22:55:25.484    10254: 12981: 12981 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:2280  当前版本名：8.0.31
[ 2023-11-16T22:55:25.815    10258: 14123: 14123 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:25.866    10258: 14123: 14123 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:25.868    10258: 14123: 14123 I/LSPosed-Bridge  ] Loading legacy module io.github.qauxv from /data/app/~~ya4pzcWXswKQ7Kaov_bOkg==/io.github.qauxv-yzERpNqumgpJjdn_ix9epg==/base.apk
[ 2023-11-16T22:55:25.890    10258: 14123: 14123 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-11-16T22:55:25.890    10258: 14123: 14123 I/LSPosed-Bridge  ] Loading legacy module me.kyuubiran.qqcleaner from /data/app/~~Ia7uSU6swfmGncqVS3RQrw==/me.kyuubiran.qqcleaner-BTWrRr-Dh8rSaoLvqao5Rw==/base.apk
[ 2023-11-16T22:55:25.893    10258: 14123: 14123 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-11-16T22:55:25.906    10258: 14123: 14123 I/LSPosed-Bridge  ] Loading legacy module com.fankes.tsbattery from /data/app/~~kJatdKk1RMgWDXHwAslHwQ==/com.fankes.tsbattery-M-WqgBWspMtM-GNTt7d8DQ==/base.apk
[ 2023-11-16T22:55:25.914    10258: 14123: 14123 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-11-16T22:55:27.328    10258: 14123: 14123 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mobileqq] All processes are completed for "com.tencent.mobileqq"
[ 2023-11-16T22:55:27.430    10258: 14437: 14437 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:55:27.497    10258: 14437: 14437 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:55:27.501    10258: 14437: 14437 I/LSPosed-Bridge  ] Loading legacy module io.github.qauxv from /data/app/~~ya4pzcWXswKQ7Kaov_bOkg==/io.github.qauxv-yzERpNqumgpJjdn_ix9epg==/base.apk
[ 2023-11-16T22:55:27.538    10258: 14437: 14437 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-11-16T22:55:27.539    10258: 14437: 14437 I/LSPosed-Bridge  ] Loading legacy module me.kyuubiran.qqcleaner from /data/app/~~Ia7uSU6swfmGncqVS3RQrw==/me.kyuubiran.qqcleaner-BTWrRr-Dh8rSaoLvqao5Rw==/base.apk
[ 2023-11-16T22:55:27.542    10258: 14437: 14437 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-11-16T22:55:27.814    10258: 14437: 14437 I/LSPosed-Bridge  ] Loading legacy module com.fankes.tsbattery from /data/app/~~kJatdKk1RMgWDXHwAslHwQ==/com.fankes.tsbattery-M-WqgBWspMtM-GNTt7d8DQ==/base.apk
[ 2023-11-16T22:55:27.960    10258: 14437: 14437 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-11-16T22:55:30.434    10258: 14437: 14437 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mobileqq] All processes are completed for "com.tencent.mobileqq:MSF"
[ 2023-11-16T22:56:06.215     1001:  5665:  5665 I/LSPosed-Bridge  ] Ankio-短信 -> 广播给自动记账：【多邻国】⏰你的 577 天连胜战绩现在岌岌可危！ 加油完成今日目标，保持连胜战绩！ 退订请回 TD
[ 2023-11-16T22:56:26.109    10254: 12981: 12981 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mm] All processes are completed for "com.tencent.mm:push"
[ 2023-11-16T22:56:26.471    10254: 16946: 16946 I/LSPosed-Bridge  ] Loading legacy module com.fkzhang.wechatxposed from /data/app/~~DP7kFeaA2PJsb201nKAsLA==/com.fkzhang.wechatxposed-xqIfTOTt-bVyJEMXwFd0yg==/base.apk
[ 2023-11-16T22:56:26.486    10254: 16946: 16946 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-11-16T22:56:26.486    10254: 16946: 16946 I/LSPosed-Bridge  ] Loading legacy module cn.dreamn.qianji_auto from /data/app/~~Wr8Uxkt0S6waft27-haUpA==/cn.dreamn.qianji_auto-_xkETDJtbZ63Vp7liQlntA==/base.apk
[ 2023-11-16T22:56:26.551    10254: 16946: 16946 I/LSPosed-Bridge  ]   Loading class cn.dreamn.qianji_auto.core.hook.HookMain
[ 2023-11-16T22:56:26.554    10254: 16946: 16946 I/LSPosed-Bridge  ] Loading legacy module me.kyuubiran.qqcleaner from /data/app/~~Ia7uSU6swfmGncqVS3RQrw==/me.kyuubiran.qqcleaner-BTWrRr-Dh8rSaoLvqao5Rw==/base.apk
[ 2023-11-16T22:56:26.559    10254: 16946: 16946 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-11-16T22:56:26.580    10254: 16946: 16946 I/LSPosed-Bridge  ] Loading legacy module com.fankes.tsbattery from /data/app/~~kJatdKk1RMgWDXHwAslHwQ==/com.fankes.tsbattery-M-WqgBWspMtM-GNTt7d8DQ==/base.apk
[ 2023-11-16T22:56:26.593    10254: 16946: 16946 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-11-16T22:56:28.090    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: init context hook
[ 2023-11-16T22:56:28.094    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: loading WeXposed com.fkzhang.wechatxposed 2.42 (109) Lsposed
[ 2023-11-16T22:56:28.095    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm Wechat version 8.0.31 (2280)
[ 2023-11-16T22:56:28.095    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: Xiaomi 2304FPN6DC Android 14 (34) arm64
[ 2023-11-16T22:56:28.255    10254: 16946: 16946 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:系统通知  当前版本号:2280  当前版本名：8.0.31
[ 2023-11-16T22:56:28.258    10254: 16946: 16946 I/LSPosed-Bridge  ]  自动记账加载成功！
应用名称:微信  当前版本号:2280  当前版本名：8.0.31
[ 2023-11-16T22:56:28.260    10254: 16946: 16946 I/LSPosed-Bridge  ] Ankio-微信 -> hook红包失败！java.lang.NoSuchMethodError: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyDetailUI#a(com.tencent.mm.plugin.luckymoney.model.l)#exact
[ 2023-11-16T22:56:28.273    10254: 16946: 16946 I/LSPosed-Bridge  ] Ankio-微信 -> hook错误！获取不到昵称。错误：PftiBShrJI.rarcBYg.GEE.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.ui.chatting.d.af
[ 2023-11-16T22:56:28.527    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: init loader
[ 2023-11-16T22:56:28.535    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-11-16T22:56:29.300    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: hooking methods ...
[ 2023-11-16T22:56:29.588    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: hooking methods done! time: 293
[ 2023-11-16T22:56:29.595    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: wxcore (174) loaded successfully!
[ 2023-11-16T22:56:29.595    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: Module loaded successfully!
[ 2023-11-16T22:56:29.595    10254: 16946: 16946 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 1117
[ 2023-11-16T22:56:29.893    10254: 16946: 16946 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mm] All processes are completed for "com.tencent.mm"
[ 2023-11-16T22:56:30.730    10254: 16946: 17035 I/LSPosed-Bridge  ] WeXposed: hooking methods ...
[ 2023-11-16T22:56:30.750    10254: 16946: 17035 I/LSPosed-Bridge  ] WeXposed: hooking methods done! time: 25
[ 2023-11-16T22:56:33.418    10254: 16946: 17021 I/LSPosed-Bridge  ] WeXposed: 微X模块 2.42_5.37 (11,174) p
[ 2023-11-16T22:56:33.419    10254: 16946: 17021 I/LSPosed-Bridge  ] WeXposed: Wechat: 8.0.31_2280 {64,arm64} (0x28001f35)[9615d9c]
[ 2023-11-16T22:56:34.442    10254: 16946: 17019 I/LSPosed-Bridge  ] WeXposed: feature loaded: base 469
[ 2023-11-16T22:56:34.680    10254: 16946: 17019 I/LSPosed-Bridge  ] WeXposed: feature loaded: donation 35

</code></pre></details>

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@hosizoraru

**Comment by hosizoraru** [comment]
![IMAGE 2023-11-17 05:58:47](https://github.com/fankes/MIUINativeNotifyIcon/assets/63982994/ad1c9c10-b5a2-4d9e-9f24-230a4c704f0a)

不显示通知图标的本质是设置图标显示的上限个数为0.模块强制设置为了非0个数的话就会和系统这一行为冲突。要修的话就是加上判断，但是关闭自定义个数我觉得比较省事。

**Comment by fankes** [comment]
> ![IMAGE 2023-11-17 05:58:47](https://github.com/fankes/MIUINativeNotifyIcon/assets/63982994/ad1c9c10-b5a2-4d9e-9f24-230a4c704f0a)
> 
> 不显示通知图标的本质是设置图标显示的上限个数为0.模块强制设置为了非0个数的话就会和系统这一行为冲突。要修的话就是加上判断，但是关闭自定义个数我觉得比较省事。

我的模块之前是没问题的，因为 HyperOS 是你修的，所以你要修好
