### ISSUE TITLE
希望可以适配以下APP

### ISSUE THREAD

**Issue by lff1986** [fankes/MIUINativeNotifyIcon#20]
智联招聘com.zhaopin.social
京东金融com.jd.jrapp
慢慢买com.manmanbuy.bijia
识货com.hupu.shihuo

**Comment by fankes** [comment]
请提供截图谢谢。

**Comment by naicfeng** [comment]
最好是提取图标文件发上来，不然为爱发电还需要下载各种APP，比较麻烦

**Comment by fankes** [comment]
适配完毕
