### ISSUE TITLE
[问题与 BUG 反馈] (Debug版本似乎无法被LSPosed框架正确的识别为模块)

### ISSUE THREAD

**Issue by Nep-Timeline** [fankes/MIUINativeNotifyIcon#201]
### 模块版本

2.110 CI - d2f8ef6

### 系统版本

HyperOS

### 系统版本类型

开发版

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed 1.9.2(7024)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

无

### 详细描述问题发生的具体原因

安装Debug版本后LSPosed框架内无法开启或不会显示

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
debug 版本存在 bug 是已知问题，请使用 release 或自己打包
