### ISSUE TITLE
[问题与 BUG 反馈] (状态栏小图标变为白色实心方块)

### ISSUE THREAD

**Issue by Nep-Timeline** [fankes/MIUINativeNotifyIcon#202]
### 模块版本

2.110 (75a2a2b)

### 系统版本

HyperOS 1.0.38.0

### 系统版本类型

稳定版

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed 1.9.2(7024)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

无

### 详细描述问题发生的具体原因

状态栏小图标有时候会莫名其妙变为白色实心方块, 但是若图标更新后则会自动恢复（例如根据背景自动反色后，任意通知图标新增或被移除）

![Screenshot_2024-03-15-08-01-46-552_com miui home](https://github.com/fankes/MIUINativeNotifyIcon/assets/53483352/4e72a9e3-2bff-48c7-b79b-902fd0f6a214)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

[LSPosed_2024-03-15T08_02_31.776716.zip](https://github.com/fankes/MIUINativeNotifyIcon/files/14609091/LSPosed_2024-03-15T08_02_31.776716.zip)

[miui_notification_icons_processing_logs.zip](https://github.com/fankes/MIUINativeNotifyIcon/files/14609092/miui_notification_icons_processing_logs.zip)

</code></pre></details>

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
#200 为什么 close 了

**Comment by fankes** [comment]
#200 为什么 close 了，我告诉了你添加一个测试结果和复现步骤

**Comment by fankes** [comment]
所以你找到问题了吗

**Comment by Nep-Timeline** [comment]
> 所以你找到问题了吗

没有，问题是随机出现的，不知道如何复现（）

**Comment by fankes** [comment]
那就等继续有人反馈了再说吧

**Comment by Nep-Timeline** [comment]
目前发现一个复现方法 只要在设置里切换通知样式问题就会出现

**Comment by Nep-Timeline** [comment]
> 我无法复现，再说吧，这个模块后面打算合并到新项目的

好的，麻烦了

**Comment by KimPig** [comment]
I'm not chinese, but this is same for me.
When I unlock the screen, the notification appears as a white box for a few seconds.

**Comment by Lovefish** [comment]
我也遇到了同样的问题。
那刚进入系统的时候，就是方块，好像过一会儿或者是下拉通知之后会恢复正常。
锁屏之后再打开，也会变成方块

**Comment by lijingbo666** [comment]
我也发生过，也是发生在解锁后，也是telegram,在打开手机上任何一个软件后，图标自动恢复正常，也是随机出现找不到复现步骤

**Comment by Nep-Timeline** [comment]
更新至CI [a506681](https://github.com/fankes/MIUINativeNotifyIcon/commit/a5066814317941ffb87b5174fb289b894c1e476f)
 后，问题仍然存在 但有所好转。情况为：图标变为白色方块一瞬后就会恢复正常 但是仍然会概率出现

**Comment by Lovefish** [comment]
> 更新至CI [a506681](https://github.com/fankes/MIUINativeNotifyIcon/commit/a5066814317941ffb87b5174fb289b894c1e476f) 后，问题仍然存在 但有所好转。情况为：图标变为白色方块一瞬后就会恢复正常 但是仍然会概率出现

怎么又是你，姐姐。

**Comment by Nep-Timeline** [comment]
> > 更新至CI [a506681](https://github.com/fankes/MIUINativeNotifyIcon/commit/a5066814317941ffb87b5174fb289b894c1e476f) 后，问题仍然存在 但有所好转。情况为：图标变为白色方块一瞬后就会恢复正常 但是仍然会概率出现
> 
> 怎么又是你，姐姐。

=。=

**Comment by armv7a** [comment]
更新至 5a1672c 版本此问题依旧存在

**Comment by fankes** [comment]
> 更新至 5a1672c 版本此问题依旧存在

因为我没有修这个问题

**Comment by TomyJan** [comment]
7678ea7 好转了点，但问题依然存在，系统版本 Beta 1.1.4.0

https://github.com/user-attachments/assets/ff721155-1ad3-443f-b018-268e90fe84c9

**Comment by Paosang** [comment]
![Screenshot_2024-10-11-17-44-15-061_com miui home](https://github.com/user-attachments/assets/03272c4f-4f68-4431-8644-ec6fe87a9d87)

https://github.com/user-attachments/assets/43c9a26c-dd22-46ff-82d0-43ecb7b833c1

OS1.1.5，

**Comment by fankes** [comment]
@Paosang @TomyJan 麻烦提供一下出问题过程复现的模块日志，直接上传到 GitHub 就行

**Comment by TomyJan** [comment]
> @Paosang @TomyJan 麻烦提供一下出问题过程复现的模块日志，直接上传到 GitHub 就行

需要装debug版本吗

**Comment by TomyJan** [comment]
[miui_notification_icons_processing_logs.log](https://github.com/user-attachments/files/17341342/miui_notification_icons_processing_logs.log)

这是 release 版本触发了几次图标变色的日志

**Comment by Paosang** [comment]
> @Paosang @TomyJan 麻烦提供一下出问题过程复现的模块日志，直接上传到 GitHub 就行

[LSPosed_2024-10-11T18_33_48.773961.zip](https://github.com/user-attachments/files/17341432/LSPosed_2024-10-11T18_33_48.773961.zip)
从lsp导的详细日志（，有复现

**Comment by fankes** [comment]
没看到错误，所以这只能等我有这种版本的系统后才能修复

**Comment by Paosang** [comment]
> 没看到错误，所以这只能等我有这种版本的系统后才能修复

debug版本激活不了正常吗，已经重启过
![Screenshot_2024-10-11-18-45-12-710_com fankes miui notify](https://github.com/user-attachments/assets/7ebb8a8b-ef63-4f16-a7dd-3eb150fe255b)

**Comment by TomyJan** [comment]
> 没看到错误，所以这只能等我有这种版本的系统后才能修复

那个方块应该是反色出问题了吧, 所以才没报错

**Comment by fankes** [comment]
debug 版本 ci 打包一直有 bug，用 release 就行，都一样

**Comment by fankes** [comment]
> > 没看到错误，所以这只能等我有这种版本的系统后才能修复
> 
> 那个方块应该是反色出问题了吧, 所以才没报错

系统有了新的地方重新设置小图标，暂时不知道是什么地方加的，所以不是反色出问题，而是设置了着色的小图标被系统强制改成 APP 彩色图标，这当然不可能支持着色属性，就变色块了
模块本质上不会修改推送的图标，所以读取缓存时就会调用之前的图标

**Comment by Illustar0** [comment]
目前模块在HyperOS 2.0.2.2是完全没法工作，估计又改了不少东西

**Comment by fankes** [comment]
> 目前模块在HyperOS 2.0.2.2是完全没法工作，估计又改了不少东西
> 
> ~~看着那彩色图标我强迫症都要犯了~~

丢给我 MiuiSystemUI.apk

**Comment by TomyJan** [comment]
> 目前模块在HyperOS 2.0.2.2是完全没法工作，估计又改了不少东西 ~看着那彩色图标我强迫症都要犯了~

我的小米 14 害怕 2.0.2.2 上正常，没有新的问题，要不你看看是不是你哪里设置有问题

**Comment by Illustar0** [comment]
更到 b10ff65 就正常了。我的锅

**Comment by fankes** [comment]
试一下 e9e27b1 的 ci

**Comment by Paosang** [comment]
![Screenshot_2024-11-06-20-55-17-968_com fankes miui notify](https://github.com/user-attachments/assets/892a4f75-2704-410b-a6aa-59ebc083560f)
依然有白块

**Comment by fankes** [comment]
那就再等等看吧，我没有 h2 的设备靠大家 pr 或者评论赛博修复确实不行

**Comment by ghhccghk** [comment]
![Screenshot_20241124-155626](https://github.com/user-attachments/assets/9907806f-baa7-47e0-9502-9e2dc2b0a549)
澎湃 2.0.20.0 出现了这个问题，但是只要开启了使用占位符修补未适配的通知图标，就能显示占位图标，但是状态栏里的图标是正常的有莫奈取色的
![Screenshot_20241124-155756](https://github.com/user-attachments/assets/df98b787-2745-442c-ab02-743a426aafdf)

**Comment by ghhccghk** [comment]
更新到 2.0.23.0出现了如下奇葩情况

https://github.com/user-attachments/assets/9c1fa837-c11c-452c-a3e4-e2fe4966d9bc

貌似切换状态栏深色模式能让图标显示正常

**Comment by fankes** [comment]
> 更新到 2.0.23.0出现了如下奇葩情况
> 
> https://github.com/user-attachments/assets/9c1fa837-c11c-452c-a3e4-e2fe4966d9bc
> 
> 貌似切换状态栏深色模式能让图标显示正常

本质上还是这个问题 https://github.com/fankes/MIUINativeNotifyIcon/issues/202#issuecomment-2407181536

**Comment by ghhccghk** [comment]
> > 更新到 2.0.23.0出现了如下奇葩情况
> > 
> >   
> >     
> >     
> > 
> >     VID_20241124_160501.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > 貌似切换状态栏深色模式能让图标显示正常
> 
> 本质上还是这个问题 [#202 (comment)](https://github.com/fankes/MIUINativeNotifyIcon/issues/202#issuecomment-2407181536)

另外我想问一下，如何在android studio 上进行编译，我想调试一下看看能不能修好

**Comment by fankes** [comment]
正常流程编译就行

**Comment by ghhccghk** [comment]
> 正常流程编译就行

![Screenshot_20241125-202015](https://github.com/user-attachments/assets/9fa72cb1-8b58-4bc5-a8cd-eb66e91add7d)
模块貌似没办法正常激活呢

**Comment by fankes** [comment]
114514 是什么，不要乱动 ci 的配置，本地编译没有那个标才对，然后勾选 always install with pm 选项，否则模块代码无法正常更新

**Comment by ghhccghk** [comment]
> 114514 是什么，不要乱动 ci 的配置，本地编译没有那个标才对，然后勾选 always install with pm 选项，否则模块代码无法正常更新

源代码拿错了，现在正常了（）

**Comment by ghhccghk** [comment]
com.android.systemui.statusbar.notification.icon.ui.viewbinder.NotificationIconContainerViewBinder$bindIcons$5$invokeSuspend$$inlined$collectTracingEach$1

尝试获取了调用堆栈，怀疑是这个类干的

**Comment by ghhccghk** [comment]
> 小米改了这里的源码没错，但是模块目前不修改创建时，只修改运行时，所以找出把通知图标替换回 app 图标的方法，干掉它即可

`public abstract class FocusUtils {
    public static RemoteViews getFocusView(Notification notification, Context context, boolean z) {
        boolean z2;
        String str;
        String str2;
        boolean isTinyScreen = MiuiConfigs.isTinyScreen(context);
        RemoteViews remoteViews = null;
        if (!isFocusNotification(notification)) {
            return null;
        }
        int i = context.getResources().getConfiguration().uiMode & 48;
        if (i != 0 && i != 32) {
            z2 = false;
        } else {
            z2 = true;
        }
        if (z) {
            remoteViews = (RemoteViews) notification.extras.getParcelable("miui.focus.rv.fullAod", RemoteViews.class);
        }
        if (z2 && remoteViews == null) {
            Bundle bundle = notification.extras;
            if (!isTinyScreen) {
                str2 = "miui.focus.rvNight";
            } else {
                str2 = "miui.focus.rv.tinyNight";
            }
            remoteViews = (RemoteViews) bundle.getParcelable(str2, RemoteViews.class);
        }
        if (z2 && remoteViews == null) {
            remoteViews = (RemoteViews) notification.extras.getParcelable("miui.focus.rvNight", RemoteViews.class);
        }
        if (remoteViews == null) {
            Bundle bundle2 = notification.extras;
            if (!isTinyScreen) {
                str = "miui.focus.rv";
            } else {
                str = "miui.focus.rv.tiny";
            }
            remoteViews = (RemoteViews) bundle2.getParcelable(str, RemoteViews.class);
        }
        if (remoteViews == null) {
            remoteViews = (RemoteViews) notification.extras.getParcelable("miui.focus.rv", RemoteViews.class);
        }
        NotifImageUtil.handleFocusAppIcon(context, remoteViews, notification.extras.getInt("miui.focus.iconId", 0), notification);
        return new RemoteViews(remoteViews);
    }
`

这段呢

**Comment by fankes** [comment]
可以先把强制设置应用图标的方法干掉

**Comment by fankes** [comment]
不可以这么改，这样就破坏模块的工作原理了

**Comment by ghhccghk** [comment]
![Uploading Screenshot_20241129-191812.png…]()
焦点通知已经解决

**Comment by fankes** [comment]
反色也解决了吗

**Comment by ghhccghk** [comment]
> 反色也解决了吗

val expandedNf = args(0).cast<StatusBarNotification?>()
                    /** Hook 状态栏小图标 */
                    compatStatusIcon(
                        context = context,
                        nf = expandedNf,
                        iconDrawable = result<Icon>()?.loadDrawable(context)
                    ).also { pair -> if (pair.second) result = Icon.createWithBitmap(pair.first?.toBitmap()) }这个代码怎么设置黑色图标

**Comment by fankes** [comment]
反色代码在下面的 dark mode 里，你看一下

**Comment by fankes** [comment]
> > 反色代码在下面的 dark mode 里，你看一下
> 
> 反不动，服了、

https://github.com/fankes/MIUINativeNotifyIcon/blob/master/app/src/main/java/com/fankes/miui/notify/hook/entity/SystemUIHooker.kt#L643

反色的深浅是有透明度和动画的，不是简单的设置黑白

**Comment by ghhccghk** [comment]
> > > 反色代码在下面的 dark mode 里，你看一下
> > 
> > 
> > 反不动，服了、
> 
> https://github.com/fankes/MIUINativeNotifyIcon/blob/master/app/src/main/java/com/fankes/miui/notify/hook/entity/SystemUIHooker.kt#L643
> 
> 反色的深浅是有透明度和动画的，不是简单的设置黑白
> 
> https://github.com/fankes/MIUINativeNotifyIcon/blob/master/app/src/main/java/com/fankes/miui/notify/hook/entity/SystemUIHooker.kt#L984
> 
> 这个方法是可以监听到状态栏颜色变化的，颜色深浅不是简单的黑白，而是 0.0f-1.0f 0.0f 即纯白 1.0f 即纯黑

这玩意分成了getStatusBarTickerDarkIcon 和getStatusBarTickerIcon 我看了都无语

**Comment by fankes** [comment]
![image](https://github.com/user-attachments/assets/9375f532-e35e-4b1e-83a9-0c5345a9677f)

来了，我现在找了一个能复现这个 bug 的 1.0.13 版本，给 K20P 整上了

**Comment by ghhccghk** [comment]
![Screenshot_2024-12-01-16-13-08-159_com tencent mm](https://github.com/user-attachments/assets/b2c10ef9-72fa-4730-b8c8-6568f84a2285)
等我调整一下颜色替换效果

**Comment by ghhccghk** [comment]
![Screenshot_2024-12-01-16-18-31-765_com tencent mm](https://github.com/user-attachments/assets/5deffd3a-e068-452f-af22-138eec965150)
好了

**Comment by fankes** [comment]
焦点通知是 2 加的吗

**Comment by ghhccghk** [comment]
> 焦点通知是 2 加的吗

对

**Comment by fankes** [comment]
> 好了

推上来看看（

**Comment by ghhccghk** [comment]
我目前查到 com.miui.systemui.graphics.AppIconsManager可能和获取图标有关，可以用有root权限的终端模拟器输入setprop debug.sysui true开启systemui debug

**Comment by fankes** [comment]
尝试 [b476c19](https://github.com/fankes/MIUINativeNotifyIcon/commit/b476c19035c3397c264908f325cdcaf26a16c623)

**Comment by Genicur** [comment]
![Screenshot_2024-12-05-16-04-31-845_com.android.settings.jpg](https://github.com/user-attachments/assets/3c5acdd0-0e22-423b-befa-f97644603de7)

![Screenshot_2024-12-05-16-04-34-796_com.android.settings.jpg](https://github.com/user-attachments/assets/bae178ba-17fc-4491-84c9-63c5852b4ae0)

会更新的常驻通知一直显示白块（极少的时候变成正常）

**Comment by fankes** [comment]
@Genicur 修的是焦点通知

**Comment by Nep-Timeline** [comment]
![IMG_20241205_162138](https://github.com/user-attachments/assets/51f9c849-57ba-4dc8-a65d-77e9f7f92622)
有个小白块

**Comment by ghhccghk** [comment]
> ![IMG_20241205_162138](https://private-user-images.githubusercontent.com/53483352/392716603-51f9c849-57ba-4dc8-a65d-77e9f7f92622.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODgzMzUsIm5iZiI6MTczMzM4ODAzNSwicGF0aCI6Ii81MzQ4MzM1Mi8zOTI3MTY2MDMtNTFmOWM4NDktNTdiYS00ZGM4LWE2NWQtNzdlOWY3ZjkyNjIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNjg0ODE5OTc4YmMyM2RmM2I2MzUyODVhZTg2MmQ0YWUxZTNlN2RjZWU5YzJiMzZmOGFmYzhjYTkzNGM4MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pVDg8N3jIEpToRZTPZF2TP7vzTGCKpwcjLdm-QnQrJ0) 有个小白块

目前无解

**Comment by ghhccghk** [comment]
> @Genicur 修的是焦点通知

这边我想问一下，我目前获取hook到了NotificationClass和ContextClass，我如何接入到图标替换接口

**Comment by fankes** [comment]
参照我上面发的位置

**Comment by ghhccghk** [comment]
> 参照我上面发的位置

修好了

**Comment by ghhccghk** [comment]
> 参照我上面发的位置

问题是`private fun compatStatusIcon(context: Context, nf: StatusBarNotification?, iconDrawable: Drawable?) = nf?.let { notifyInstance ->` 是StatusBarNotification 而我这里代码拿到的是Notification 能用？

**Comment by fankes** [comment]
不能，拿 sbn 也是取 nf，你可以加个参数看看满足的条件，我已经下机了🥶

**Comment by ghhccghk** [comment]
> 不能，拿 sbn 也是取 nf，你可以加个参数看看满足的条件，我已经下机了🥶

欧克，看起来是个大工程

**Comment by Nep-Timeline** [comment]
![IMG_20241205_215737](https://github.com/user-attachments/assets/7b7c771a-4fd8-4547-8819-2c5c2fed2ef9)
话说 图标颜色切换有点不自然 如图

**Comment by ghhccghk** [comment]
> ![IMG_20241205_215737](https://private-user-images.githubusercontent.com/53483352/392845950-7b7c771a-4fd8-4547-8819-2c5c2fed2ef9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDg3MzQsIm5iZiI6MTczMzQwODQzNCwicGF0aCI6Ii81MzQ4MzM1Mi8zOTI4NDU5NTAtN2I3Yzc3MWEtNGZkOC00NTQ3LTg4MTktMmM1YzJmZWQyZWY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYWNiNzkwMjg4MzFlZTUzYzgzMjJhMzZlZGYxZWI0NzZiZGI1YTQ1Y2YyOGU4ZGFiYmI1MDVjNjMyMjFjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5PcAVKKs7didRF0xNNHp7RZj0MhIbuJByv4WlQ16CWQ) 话说 图标颜色切换有点不自然 如图

试试看下载ci版本看看是不是正常了

**Comment by Nep-Timeline** [comment]
> > ![IMG_20241205_215737](https://private-user-images.githubusercontent.com/53483352/392845950-7b7c771a-4fd8-4547-8819-2c5c2fed2ef9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDg3MzQsIm5iZiI6MTczMzQwODQzNCwicGF0aCI6Ii81MzQ4MzM1Mi8zOTI4NDU5NTAtN2I3Yzc3MWEtNGZkOC00NTQ3LTg4MTktMmM1YzJmZWQyZWY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYWNiNzkwMjg4MzFlZTUzYzgzMjJhMzZlZGYxZWI0NzZiZGI1YTQ1Y2YyOGU4ZGFiYmI1MDVjNjMyMjFjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5PcAVKKs7didRF0xNNHp7RZj0MhIbuJByv4WlQ16CWQ) 话说 图标颜色切换有点不自然 如图
> 
> 试试看下载ci版本看看是不是正常了

一样的

**Comment by ghhccghk** [comment]
> > > ![IMG_20241205_215737](https://private-user-images.githubusercontent.com/53483352/392845950-7b7c771a-4fd8-4547-8819-2c5c2fed2ef9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDg3MzQsIm5iZiI6MTczMzQwODQzNCwicGF0aCI6Ii81MzQ4MzM1Mi8zOTI4NDU5NTAtN2I3Yzc3MWEtNGZkOC00NTQ3LTg4MTktMmM1YzJmZWQyZWY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYWNiNzkwMjg4MzFlZTUzYzgzMjJhMzZlZGYxZWI0NzZiZGI1YTQ1Y2YyOGU4ZGFiYmI1MDVjNjMyMjFjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5PcAVKKs7didRF0xNNHp7RZj0MhIbuJByv4WlQ16CWQ) 话说 图标颜色切换有点不自然 如图
> > 
> > 
> > 试试看下载ci版本看看是不是正常了
> 
> 一样的 白块问题倒是没了

白块问题没了应该就OK👌了，这个问题估计难搞

**Comment by Nep-Timeline** [comment]
> > > > ![IMG_20241205_215737](https://private-user-images.githubusercontent.com/53483352/392845950-7b7c771a-4fd8-4547-8819-2c5c2fed2ef9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDg3MzQsIm5iZiI6MTczMzQwODQzNCwicGF0aCI6Ii81MzQ4MzM1Mi8zOTI4NDU5NTAtN2I3Yzc3MWEtNGZkOC00NTQ3LTg4MTktMmM1YzJmZWQyZWY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYWNiNzkwMjg4MzFlZTUzYzgzMjJhMzZlZGYxZWI0NzZiZGI1YTQ1Y2YyOGU4ZGFiYmI1MDVjNjMyMjFjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5PcAVKKs7didRF0xNNHp7RZj0MhIbuJByv4WlQ16CWQ) 话说 图标颜色切换有点不自然 如图
> > > 
> > > 
> > > 试试看下载ci版本看看是不是正常了
> > 
> > 
> > 一样的 白块问题倒是没了
> 
> 白块问题没了应该就OK👌了，这个问题估计难搞

可能是因为澎湃其他的状态栏图标黑白切换都有过度 但是应用小图标没有

**Comment by fankes** [comment]
有的，1.0 的过渡没坏

**Comment by Nep-Timeline** [comment]
> 有的，1.0 的过渡没坏

好的 那就是2.0坏了

**Comment by fankes** [comment]
试试 [4dcb057](https://github.com/fankes/MIUINativeNotifyIcon/commit/4dcb05797cef1849dc515bbf206cfc439f61b9e4)

**Comment by Paosang** [comment]
> 试试[4dcb057](https://github.com/fankes/MIUINativeNotifyIcon/commit/4dcb05797cef1849dc515bbf206cfc439f61b9e4)

貌似修好了

**Comment by fankes** [comment]
这个问题现作为已修复关闭，如果依然存在相同问题，请继续回复，会重新打开。

**Comment by Nep-Timeline** [comment]
> > ![IMG_20241205_162138](https://private-user-images.githubusercontent.com/53483352/392716603-51f9c849-57ba-4dc8-a65d-77e9f7f92622.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODgzMzUsIm5iZiI6MTczMzM4ODAzNSwicGF0aCI6Ii81MzQ4MzM1Mi8zOTI3MTY2MDMtNTFmOWM4NDktNTdiYS00ZGM4LWE2NWQtNzdlOWY3ZjkyNjIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNjg0ODE5OTc4YmMyM2RmM2I2MzUyODVhZTg2MmQ0YWUxZTNlN2RjZWU5YzJiMzZmOGFmYzhjYTkzNGM4MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pVDg8N3jIEpToRZTPZF2TP7vzTGCKpwcjLdm-QnQrJ0) 有个小白块
> 
> 目前无解

提一下 这个问题在升级至HyperOS 2.0.26.8 Beta后解决了 看起来是HyperOS自身的问题
