### ISSUE TITLE
[BUG] 图标动态变化时会随机闪出一个白色圆角矩形

### ISSUE THREAD

**Issue by nanguaguag** [fankes/MIUINativeNotifyIcon#203]
- MIUI14
- MIUI 原生通知图标 Latest (2.110)
- LSposed 1.9.3(7204)

正常vs异常：

![IMG_20240330_110621.jpg](https://github.com/fankes/MIUINativeNotifyIcon/assets/120099147/c0a848eb-2e27-4a1c-b8eb-951d4eba8dd6)

![IMG_20240330_110606.jpg](https://github.com/fankes/MIUINativeNotifyIcon/assets/120099147/9edc88ee-25c9-44f3-b573-b96cd98723f9)

**如何复现**：

随便找一个可以动态变化的图标（比如surfboard实时流量）

**Comment by nanguaguag** [comment]
而且是这个白色方块是随机出现的，看上去就是图标一闪一闪的。

**Comment by fankes** [comment]
找不到了，之前有一个 issues 说过，这个修不了

**Comment by fankes** [comment]
[CI](https://github.com/fankes/MIUINativeNotifyIcon/actions/runs/10784558182) 已尝试修复这个问题。

**Comment by Nep-Timeline** [comment]
https://github.com/user-attachments/assets/d9563aa6-bcc5-419b-8eb4-07ecd8b94fb4

![Screenshot_2024-09-10-16-21-30-858_com fankes miui notify](https://github.com/user-attachments/assets/f6dc50d5-de9c-4491-bfcf-e4036821abca)

经测试，此问题仍然存在

**Comment by fankes** [comment]
> https://github.com/user-attachments/assets/d9563aa6-bcc5-419b-8eb4-07ecd8b94fb4
> 
> ![Screenshot_2024-09-10-16-21-30-858_com fankes miui notify](https://github.com/user-attachments/assets/f6dc50d5-de9c-4491-bfcf-e4036821abca)
> 
> 经测试，此问题仍然存在
> 测试用软件: Aurora Store

MiuiSystemUI.apk 发我一份

**Comment by Nep-Timeline** [comment]
> @Nep-Timeline
> 
> 烦请将 MiuiSystemUI.apk 发我一份
> 
> 动态小图标展开后还会是动态的，你这个功能也是坏的，我目前没有使用 HyperOS 设备进行测试，在 MIUI 14 上表现正常

https://www.123pan.com/s/h1szVv-Mv34H
提取码:A2AW

提取自小米14 HyperOS 1.0.45.0

**Comment by fankes** [comment]
@Nep-Timeline 已尝试修复，请测试最新版本的 CI

**Comment by Nep-Timeline** [comment]
> @Nep-Timeline 已尝试修复，请测试最新版本的 [CI](https://github.com/fankes/MIUINativeNotifyIcon/actions/runs/10824266919)


https://github.com/user-attachments/assets/93585f28-4190-4f36-b230-689298f3f69b

白块闪烁问题已解决
下载动画有点点抽搐 但无任何影响

**Comment by fankes** [comment]
好的，感谢反馈，下载图标的动画是应用的问题，重新推送通知会重新播放图标动画

**Comment by cuddly-guacamole** [comment]
图标似乎还是有点闪烁？应该是应用的问题。已经不会想之前那样出现白块了。感谢作者修复。

https://github.com/user-attachments/assets/22e13050-e1a9-463a-a628-7b4e311d3d43

**Comment by Nep-Timeline** [comment]
> 图标似乎还是有点闪烁？应该是应用的问题。已经不会想之前那样出现白块了。感谢作者修复。
> 
>  VID_20240912_130339.mp4

是的 我也有这个问题 但是因为我这个颜色比较深 不细看看不出来

**Comment by fankes** [comment]
@cuddly-guacamole 
关掉这个功能，锁屏重新解锁应该就可以了

![Screenshot_2024-09-12-13-28-43-953_com.fankes.miui.notify-edit.jpg](https://github.com/user-attachments/assets/2e194420-6460-49a6-a8e7-44b99a623405)
