### ISSUE TITLE
[问题与 BUG 反馈] 通知栏中的图标不会变成黑色

### ISSUE THREAD

**Issue by CcendercatcC** [fankes/MIUINativeNotifyIcon#207]
### 模块版本

2.110 Cla2bf9d2

### 系统版本

HyperOS1.1.3.0（安卓15）

### 系统版本类型

开发内测版

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed 1.10.0(7068)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

启动遮罩优化

### 详细描述问题发生的具体原因

启动模块，打开一个白色的界面，通知栏中的图标不会变成黑色

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
仅凭文字描述不能认定为这是什么情况，提供必要 log 和出现问题的截屏及详细复现步骤，然后重新打开此 issue

**Comment by CcendercatcC** [comment]
附件分别为 log 出现bug时的截图与正常工作时的截图
在使用该模块的澎湃OS体验增强beta中 通知栏中的图标在任何时候都是白色的
[miui_notification_icons_processing_logs.log](https://github.com/user-attachments/files/17190733/miui_notification_icons_processing_logs.log)
![Screenshot_2024-09-30-21-32-12-731_com android browser](https://github.com/user-attachments/assets/86f086b4-763b-49c3-bd5c-2c9eb8902a8c)
![Screenshot_2024-09-30-21-29-38-906_com miui home](https://github.com/user-attachments/assets/fda735ef-99e9-4d51-a1bd-124e49d6e268)

**Comment by fankes** [comment]
麻烦提供 MiuiSystemUI.apk 给我

**Comment by CcendercatcC** [comment]
[MiuiSystemUI.zip](https://github.com/user-attachments/files/17200180/MiuiSystemUI.zip)

**Comment by MoYoez** [comment]
hyperos 1.1.3 beta（corot）也是存在这个问题

不会跟随壁纸进行处理 而是单一白色![Screenshot_2024-10-01-19-07-55-558_com.github.android.jpg](https://github.com/user-attachments/assets/1886c81a-2e7f-40c7-b88d-32de2df51ab2)

![Screenshot_2024-10-01-19-08-08-627_com.android.settings.jpg](https://github.com/user-attachments/assets/af43b770-ef8f-4a77-8a3f-1a64cfc0d539)

**Comment by fankes** [comment]
@Nep-Timeline 你的 PR 用注释标记了一下 `NotificationIconAreaController` 不再存在，我看了一下当前 issue 作者提供的 apk，`NotificationIconAreaController` 变成了一个空的 `interface`，并且我找到了 `LegacyNotificationIconAreaControllerImpl`，之前的反色是通过 `onDarkChanged` 方法控制，获取 `mNotificationIcons` 容器的 `StatusBarIconView`，但是目前 `mNotificationIcons` 容器不存在了，仅 hook `StatusBarIconView` 的 `onDarkChanged` 方法设置着色是否能够生效也是未知操作，另有 `LegacyNotificationIconAreaControllerImpl$$ExternalSyntheticLambda0` 类中的 `run` 似乎是在做类似的操作，我需要一个验证，因为我手里没有这样系统的设备存在，所以还请你有空时看一下我提到的这两个地方。

**Comment by Nep-Timeline** [comment]
> @Nep-Timeline 你的 PR 用注释标记了一下 `NotificationIconAreaController` 不再存在，我看了一下当前 issue 作者提供的 apk，`NotificationIconAreaController` 变成了一个空的 `interface`，并且我找到了 `LegacyNotificationIconAreaControllerImpl`，之前的反色是通过 `onDarkChanged` 方法控制，获取 `mNotificationIcons` 容器的 `StatusBarIconView`，但是目前 `mNotificationIcons` 容器不存在了，仅 hook `StatusBarIconView` 的 `onDarkChanged` 方法设置着色是否能够生效也是未知操作，另有 `LegacyNotificationIconAreaControllerImpl$$ExternalSyntheticLambda0` 类中的 `run` 似乎是在做类似的操作，我需要一个验证，因为我手里没有这样系统的设备存在，所以还请你有空时看一下我提到的这两个地方。

按照你提供的思路 我对`StatusBarIconView` 的 `onDarkChanged` 进行Hook，目前在我的设备上测试反色可以正常执行

**Comment by fankes** [comment]
@Nep-Timeline 不进行这个操作保持之前最新的 ci 版本反色是否是正常的呢

**Comment by Nep-Timeline** [comment]
> @Nep-Timeline 不进行这个操作保持之前最新的 ci 版本反色是否是正常的呢

否

**Comment by Nep-Timeline** [comment]
![image](https://github.com/user-attachments/assets/c88ba500-16ca-4d69-9368-a8764c301241)

**Comment by fankes** [comment]
试一下这个 [CI](https://github.com/fankes/MIUINativeNotifyIcon/actions/runs/11160804670) 是否能修复这个问题

**Comment by MoYoez** [comment]
> 试一下这个 [CI](https://github.com/fankes/MIUINativeNotifyIcon/actions/runs/11160804670) 是否能修复这个问题

![Screenshot_2024-10-03-19-34-14-957_com.fankes.miui.notify-edit.jpg](https://github.com/user-attachments/assets/ad10303f-249a-46de-955c-29bfb69abef4)

it can work：p
