### ISSUE TITLE
[待讨论] HyperOS 焦点通知图标适配

### ISSUE THREAD

**Issue by axelpln** [fankes/MIUINativeNotifyIcon#211]
### 模块版本

2.110

### 系统版本

HyperOS 1.0.7.0

### 系统版本类型

稳定版

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed 1.10.1(7115)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

HyperCeiler(com.sevtinge.hyperceiler)、米客(name.monwf.customiuizer)、灵动岛(com.highcapable.yukihookapi.Island_module)

### 详细描述问题发生的具体原因

![Screenshot_2024-11-04-16-43-04-909_com miui home](https://github.com/user-attachments/assets/e6dab587-5124-4cb8-b524-f3d1a4a78ef9)
![Screenshot_2024-11-04-16-43-09-579_com fankes miui notify](https://github.com/user-attachments/assets/53d095d9-7ddd-4b40-bf7f-a2e8eac5ac15)

如图，例如在有 APP 正在使用屏幕内容的状态下，手机管家在左上角弹出的特殊状态提示，其图标无法跟随状态栏其他图标的颜色变化，只能一直以白色显示

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

================================================================
    Generated by MIUINativeNotifyIcon
    Project Url: https://github.com/fankes/MIUINativeNotifyIcon
================================================================

[Device Brand]: Redmi
[Device Model]: 23049RAD8C
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[HyperOS Version]: HyperOS 1.0.7.0.UMRCNXM 稳定版
[System Locale]: en_US

2024-11-04T17:06:35.938 ------ [D] (Processing Status Bar Icon) ↓
[Title]: null
[Content]: null
[App Name]: Security
[Package Name]: com.miui.securitycenter
[Sender Package Name]: com.miui.securitycenter
[Custom Icon]: true
[Grayscale Icon]: false
[From Xmsf]: false
[String]: Notification(channel=com.miui.securitycenter shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x802 color=0x00000000 vis=PRIVATE)
2024-11-04T17:06:35.944 ------ [D] (Processing Status Bar Icon) ↓
[Title]: null
[Content]: null
[App Name]: Scene
[Package Name]: com.omarea.vtools
[Sender Package Name]: com.omarea.vtools
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=keep-alive shortcut=null contentView=com.omarea.vtools/0x7f0d00c9 vibrate=null sound=null defaults=0x0 flags=0x22 color=0x00000000 vis=PRIVATE)
2024-11-04T17:06:35.950 ------ [D] (Processing Status Bar Icon) ↓
[Title]: 夸克悬浮窗搜题
[Content]: 已开启悬浮窗搜题模式，AI截屏秒出答案
[App Name]: 夸克
[Package Name]: com.quark.browser
[Sender Package Name]: com.quark.browser
[Custom Icon]: true
[Grayscale Icon]: false
[From Xmsf]: false
[String]: Notification(channel=answer shortcut=null contentView=null vibrate=null sound=default defaults=0x1 flags=0x60 color=0x00000000 vis=PRIVATE)
2024-11-04T17:06:49.012 ------ [D] (Processing Status Bar Icon) ↓
[Title]: null
[Content]: null
[App Name]: Security
[Package Name]: com.miui.securitycenter
[Sender Package Name]: com.miui.securitycenter
[Custom Icon]: true
[Grayscale Icon]: false
[From Xmsf]: false
[String]: Notification(channel=com.miui.securitycenter shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x802 color=0x00000000 vis=PRIVATE)
2024-11-04T17:06:49.019 ------ [D] (Processing Status Bar Icon) ↓
[Title]: null
[Content]: null
[App Name]: Scene
[Package Name]: com.omarea.vtools
[Sender Package Name]: com.omarea.vtools
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=keep-alive shortcut=null contentView=com.omarea.vtools/0x7f0d00c9 vibrate=null sound=null defaults=0x0 flags=0x22 color=0x00000000 vis=PRIVATE)
2024-11-04T17:06:49.025 ------ [D] (Processing Status Bar Icon) ↓
[Title]: 夸克悬浮窗搜题
[Content]: 已开启悬浮窗搜题模式，AI截屏秒出答案
[App Name]: 夸克
[Package Name]: com.quark.browser
[Sender Package Name]: com.quark.browser
[Custom Icon]: true
[Grayscale Icon]: false
[From Xmsf]: false
[String]: Notification(channel=answer shortcut=null contentView=null vibrate=null sound=default defaults=0x1 flags=0x60 color=0x00000000 vis=PRIVATE)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
这个反色应该是不存在的，因为这个状态的通知图标是 hyper 自己写的，不支持反色且 hyper 也没给它打算进行支持，因为原图标就是彩色的，后面可以看看适配一下或者直接对其图标还原摆烂

**Comment by axelpln** [comment]
原图标直接就是正在使用屏幕内容的 APP 图标，比如夸克，看起来是模块把这块的 icon 替换成了手机管家的，而手机管家本身没有这个 icon 的反色版本？
顺带一提如果有电话打进来的情况同样的地方是一个电话图标，同样不支持反色，原图标暂时还不知道来自谁，我还没测试过，可能是电话 APP

**Comment by fankes** [comment]
这个图标就是通知图标，只不过它这个模式是 hyper 改的，不支持反色

**Comment by fankes** [comment]
试试 [4dcb057](https://github.com/fankes/MIUINativeNotifyIcon/commit/4dcb05797cef1849dc515bbf206cfc439f61b9e4)
没有问题就 close 了

**Comment by axelpln** [comment]
还是不行
![Screenshot_2024-12-07-08-30-29-471_com.xunmeng.pinduoduo-edit.jpg](https://github.com/user-attachments/assets/0f39e553-3459-4712-938f-cfb1c3e08921)

![Screenshot_2024-12-07-08-28-42-634_com.fankes.miui.notify.jpg](https://github.com/user-attachments/assets/dc91432b-d34e-43c5-a8b3-41840611176f)

**Comment by fankes** [comment]
Casting 是什么软件吗，怎么发送的这种焦点通知

**Comment by fankes** [comment]
@ghhccghk 你看看

**Comment by axelpln** [comment]
> Casting 是什么软件吗，怎么发送的这种焦点通知

就是我上面说的，有应用在使用屏幕上的信息，比如夸克的浮窗搜题（上面的 log 应该也有）
不过这个焦点通知本身并不是使用对应权限的 APP 发送的，而是手机管家，只不过正常情况下状态文字（casting 等等）旁边的图标应该是占用了相应权限的 APP 图标（比如夸克），但这个通知本身并不来自夸克
这种焦点通知应该是手机管家推送的用来提醒用户有 APP 在使用重要权限或者有什么重要性比较高的活动比如来电（incomingcall）什么的

我等会测试一下默认主题状态下原来的显示方式，因为之前我是应用了第三方主题测试的，测试项也不全，不过结果可能也大差不差

**Comment by axelpln** [comment]
换回默认主题测试了一下，和之前的结果有些出入，casting 的图标不是使用权限的 APP 图标而是手机管家内置的对应正在使用的权限的彩色图标，来电则是电话图标
![Screenshot_2024-12-07-17-15-01-236_com.quark.browser.jpg](https://github.com/user-attachments/assets/8a18ab8a-23fb-4f26-abf2-fb72cabb85b4)

![Screenshot_2024-12-07-17-15-11-153_com.miui.home-edit.jpg](https://github.com/user-attachments/assets/47126d35-a808-450f-9a84-d39c136606f3)

![Screenshot_2024-12-07-17-16-29-517_me.weishu.kernelsu.jpg](https://github.com/user-attachments/assets/e9ffe8af-1236-4405-b26c-53a00e2bb012)

**Comment by axelpln** [comment]
第三方主题下权限图标变成了使用对应权限的 APP 的图标（但具体通知内容仍和上条 comment 的内容一致），推测是图标样式不一样不太好做兼容，但也没摆烂直接上手机管家的图标。至于电话这个就有点奇怪，不是拨号器的图标
![Screenshot_2024-12-07-17-20-44-763_com.quark.browser.jpg](https://github.com/user-attachments/assets/e722df8a-c4d5-407d-88cf-ec9ceccb332a)

![Screenshot_2024-12-07-17-21-42-954_me.weishu.kernelsu.jpg](https://github.com/user-attachments/assets/fba29715-1f42-4a9c-8c45-b2f4a8864d38)
顺带提一嘴原生通知图标是可以把来电状态焦点通知的图标替换为单色听筒图标，但是同样只有白色且不支持反色

**Comment by fankes** [comment]
@ghhccghk 你看一下，反色还是坏的

那后面加一个焦点通知可替用原始彩色图标就行了

**Comment by ghhccghk** [comment]
![Uploading Screenshot_2024-12-07-19-20-16-493_com.tencent.mm.jpg…]()
复现成功等我测试

**Comment by fankes** [comment]
图没传上来

**Comment by ghhccghk** [comment]
> 图没传上来

把这几个软件加入图标适配即可

**Comment by fankes** [comment]
@axelpln 麻烦再试试最新的 ci 有没有问题

**Comment by axelpln** [comment]
@fankes 还是不行
https://github.com/user-attachments/assets/af9dfd97-8922-49db-a17b-798c12d746b8

**Comment by fankes** [comment]
你的录屏后面都是黑的

**Comment by axelpln** [comment]
> 你的录屏后面都是黑的

抱歉，重新传了

**Comment by fankes** [comment]
@ghhccghk 要不你去找他定向测试一下 🥶

**Comment by ghhccghk** [comment]
> @ghhccghk 要不你去找他定向测试一下 🥶

加我邮箱qq

**Comment by ghhccghk** [comment]
可能是我系统太新了，没适配老版本无语了

**Comment by axelpln** [comment]
@ghhccghk B站私信你了，找不到你邮箱😓
不知道有没有发出去，可能被吞了，但我关注你了，头像和 GitHub 头像一致

**Comment by ghhccghk** [comment]
> @ghhccghk B站私信你了，找不到你邮箱😓

加了

**Comment by ghhccghk** [comment]
小米系统自带的small图标为webp 导致反色无效。。。。。

**Comment by fankes** [comment]
所以修好了吗

**Comment by axelpln** [comment]
> 所以修好了吗
还没，OS1 有点难搞。。。

**Comment by ghhccghk** [comment]
> 所以修好了吗

修了一半发现某些图标有问题，然后就重新改代码，2.0没问题，1.0就（

**Comment by ghhccghk** [comment]
目前测试结果
要软件重新发送通知有效果（）

**Comment by fankes** [comment]
没懂

**Comment by ghhccghk** [comment]
> 没懂

就是图标刷新机制怪的很，某些修改颜色可以用某些不行

**Comment by fankes** [comment]
![IMAGE 2024-12-11 15:31:03](https://github.com/user-attachments/assets/9c333c18-6450-4478-86bf-c37541a35399)
![IMAGE 2024-12-11 15:31:07](https://github.com/user-attachments/assets/cbbc9315-aee8-438b-866a-758998f10940)

先抛开这个问题，你是不是对所有图标都使用了你写的强制反色，导致识别为彩色的图标也被着色了，`isDarkGrayscale` 为 `false` 时，不能对原始图标进行任何修改，你看看这个问题 @ghhccghk

**Comment by fankes** [comment]
> > 没懂
> 
> 就是图标刷新机制怪的很，某些修改颜色可以用某些不行

我不理解，我觉得你应该重新看一下 `isDarkGrayscale` 的问题，反色取 dark mode 的就行

**Comment by ghhccghk** [comment]
> > > 没懂
> > 
> > 
> > 就是图标刷新机制怪的很，某些修改颜色可以用某些不行
> 
> 我不理解，我觉得你应该重新看一下 `isDarkGrayscale` 的问题，反色取 dark mode 的就行

好的，到时候我改改（

**Comment by ghhccghk** [comment]
![image](https://github.com/user-attachments/assets/c39f9437-d135-4e6c-a4e2-f0176e78dded)
应该是图标没带tint导致的，然后图标不确定是在哪里获取的（（（（

**Comment by ghhccghk** [comment]
![image](https://github.com/user-attachments/assets/a166d1a8-0648-45ce-a3b8-ea17ebd1b7d4)
@fankes 我打算接下来的版本给log 加入这个

**Comment by fankes** [comment]
没毛病

**Comment by ghhccghk** [comment]
> 没毛病

![image](https://github.com/user-attachments/assets/9a154dd1-681b-4bd8-83c4-9caf03f3be14)
话说这个怎么转换方法

**Comment by fankes** [comment]
你写完我到时候再改吧

**Comment by fankes** [comment]
后面不要用 any 转换为实例
不转的情况下你可以直接调用
mIcon.method { ... }

**Comment by ghhccghk** [comment]
> 后面不要用 any 转换为实例 不转的情况下你可以直接调用 mIcon.method { ... }
我看看

**Comment by ghhccghk** [comment]
https://github.com/fankes/MIUINativeNotifyIcon/pull/222

修复代码已经提交

**Comment by fankes** [comment]
你先测试，我后面再修改

**Comment by axelpln** [comment]
可以了可以了![Screenshot_2024-12-12-21-53-16-405_com.quark.browser.jpg](https://github.![Screenshot_2024-12-12-21-53-12-111_com.quark.browser.jpg](https://github.com/user-attachments/assets/eaa987c5-49bb-4aa8-be15-2eb211eef1eb)

ing Screenshot_2024-12-12-21-53-12-111_com.quark.browser.jpg …]()

**Comment by Nep-Timeline** [comment]
![Screenshot_2024-12-13-16-01-38-462_com fankes miui notify](https://github.com/user-attachments/assets/7b22b572-2878-43ab-b37d-7b6d44fd1c7a)
反色好像还有问题（左上角网易云图标）

**Comment by fankes** [comment]
不修了，你修吧 😡

**Comment by Nep-Timeline** [comment]
0c43bc5 没问题
8b6d35f 有问题

**Comment by ghhccghk** [comment]
> 不修了，你修吧 😡

我不会（跑

**Comment by fankes** [comment]
我的问题，现已修复 [f00f6ef](https://github.com/fankes/MIUINativeNotifyIcon/commit/f00f6efcf32de1e8c8df400ed6c7bd2f182dfd48)

**Comment by ghhccghk** [comment]
> 我的问题，现已修复 [f00f6ef](https://github.com/fankes/MIUINativeNotifyIcon/commit/f00f6efcf32de1e8c8df400ed6c7bd2f182dfd48)

2.0才有这个呢
