### ISSUE TITLE
via

### ISSUE THREAD

**Issue by lin4578** [fankes/MIUINativeNotifyIcon#213]
### APP 名称

via

### APP 包名

mark.via

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/mark.via

### 简单描述适配的通知图标使用场景

下载文件进度

### 通知单色图标适配素材 (大小 50x50~72x72)

https://www.coolapk.com/apk/mark.via

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
不推荐再使用远古版本的模块，且 via 没有滥用彩色图标行为
