### ISSUE TITLE
[问题与 BUG 反馈] 焦点通知图标失效

### ISSUE THREAD

**Issue by bwmgd** [fankes/MIUINativeNotifyIcon#214]
### 模块版本

2.110 CI 259eb1d

### 系统版本

HyperOS 2.0.6.2.VNBCNXM Beta

### 系统版本类型

稳定内测版

### Android 版本

15

### Xposed 框架名称与版本号

LSPosed 1.9.2-it (7274)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

启动遮罩进化 HyperCeiler

### 详细描述问题发生的具体原因

焦点通知（例如电话/闹钟等）会出现实心块的问题 在切换应用的时候会显示系统原本的彩色图标，如下图所示，图1为彩色图标，图2为占位符图标
![Screenshot_2024-11-20-11-30-22-115_com miui home](https://github.com/user-attachments/assets/1ea430d1-edb1-4d6f-aca1-f6d03e3821a1)
![Screenshot_2024-11-20-11-30-19-723_com yjllq internet](https://github.com/user-attachments/assets/9c93c6cb-11ea-4efd-a5b5-bef42e23b067)

推测与scene的图标问题类似 当通知动态变化的时候就会变成实心块，切换应用时通知暂停变化，显示正常图标（焦点通知应该是没有适配，所以显示原本的彩色图标）

### 提供模块问题 Log 或必要 Log

完整日志：
[miui_notification_icons_processing_logs.log](https://github.com/user-attachments/files/17824397/miui_notification_icons_processing_logs.log)

日志截取：
<details><summary>展开查看</summary><pre><code>
================================================================
    Generated by MIUINativeNotifyIcon
    Project Url: https://github.com/fankes/MIUINativeNotifyIcon
================================================================

[Device Brand]: Xiaomi
[Device Model]: 23116PN5BC
[Display]: AQ3A.240627.003
[Android Version]: 15
[Android API Level]: 35
[HyperOS Version]: HyperOS 2.0.6.2.VNBCNXM 稳定版
[System Locale]: zh_CN

[Title]: 11:40闹铃再响
[Content]: 点击取消此闹钟
[App Name]: 时钟
[Package Name]: com.android.deskclock
[Sender Package Name]: com.android.deskclock
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=channel_id_deskclock_snooze shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT color=0x00000000 vis=PRIVATE)
2024-11-20T11:30:34.243 ------ [D] (Processing Status Bar Icon) ↓
[Title]: MIUI 原生通知图标
[Content]: 均衡模式  -2.73W 100% 35.9°C
[App Name]: Scene
[Package Name]: com.omarea.vtools
[Sender Package Name]: com.omarea.vtools
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=scene-scheduler shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT|NO_CLEAR color=0x00000000 groupKey=silent vis=PRIVATE)
2024-11-20T11:30:34.249 ------ [D] (Processing Status Bar Icon) ↓
[Title]: 11:40闹铃再响
[Content]: 点击取消此闹钟
[App Name]: 时钟
[Package Name]: com.android.deskclock
[Sender Package Name]: com.android.deskclock
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=channel_id_deskclock_snooze shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT color=0x00000000 vis=PRIVATE)
2024-11-20T11:30:34.260 ------ [D] (Processing Status Bar Icon) ↓
[Title]: MIUI 原生通知图标
[Content]: 均衡模式  -2.73W 100% 35.9°C
[App Name]: Scene
[Package Name]: com.omarea.vtools
[Sender Package Name]: com.omarea.vtools
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=scene-scheduler shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT|NO_CLEAR color=0x00000000 groupKey=silent vis=PRIVATE)
2024-11-20T11:30:34.267 ------ [D] (Processing Status Bar Icon) ↓
[Title]: 11:40闹铃再响
[Content]: 点击取消此闹钟
[App Name]: 时钟
[Package Name]: com.android.deskclock
[Sender Package Name]: com.android.deskclock
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=channel_id_deskclock_snooze shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT color=0x00000000 vis=PRIVATE)
2024-11-20T11:30:34.279 ------ [D] (Processing Status Bar Icon) ↓
[Title]: MIUI 原生通知图标
[Content]: 均衡模式  -2.73W 100% 35.9°C
[App Name]: Scene
[Package Name]: com.omarea.vtools
[Sender Package Name]: com.omarea.vtools
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=scene-scheduler shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT|NO_CLEAR color=0x00000000 groupKey=silent vis=PRIVATE)
2024-11-20T11:30:34.285 ------ [D] (Processing Status Bar Icon) ↓
[Title]: 11:40闹铃再响
[Content]: 点击取消此闹钟
[App Name]: 时钟
[Package Name]: com.android.deskclock
[Sender Package Name]: com.android.deskclock
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=channel_id_deskclock_snooze shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT color=0x00000000 vis=PRIVATE)
2024-11-20T11:30:34.293 ------ [D] (Processing Status Bar Icon) ↓
[Title]: MIUI 原生通知图标
[Content]: 均衡模式  -2.73W 100% 35.9°C
[App Name]: Scene
[Package Name]: com.omarea.vtools
[Sender Package Name]: com.omarea.vtools
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=scene-scheduler shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT|NO_CLEAR color=0x00000000 groupKey=silent vis=PRIVATE)
2024-11-20T11:30:34.297 ------ [D] (Processing Status Bar Icon) ↓
[Title]: 11:40闹铃再响
[Content]: 点击取消此闹钟
[App Name]: 时钟
[Package Name]: com.android.deskclock
[Sender Package Name]: com.android.deskclock
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=channel_id_deskclock_snooze shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT color=0x00000000 vis=PRIVATE)
2024-11-20T11:30:34.305 ------ [D] (Processing Status Bar Icon) ↓
[Title]: MIUI 原生通知图标
[Content]: 均衡模式  -2.73W 100% 35.9°C
[App Name]: Scene
[Package Name]: com.omarea.vtools
[Sender Package Name]: com.omarea.vtools
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=scene-scheduler shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT|NO_CLEAR color=0x00000000 groupKey=silent vis=PRIVATE)
2024-11-20T11:30:34.310 ------ [D] (Processing Status Bar Icon) ↓
[Title]: 11:40闹铃再响
[Content]: 点击取消此闹钟
[App Name]: 时钟
[Package Name]: com.android.deskclock
[Sender Package Name]: com.android.deskclock
[Custom Icon]: false
[Grayscale Icon]: true
[From Xmsf]: false
[String]: Notification(channel=channel_id_deskclock_snooze shortcut=null contentView=null vibrate=null sound=null defaults=0 flags=ONGOING_EVENT color=0x00000000 vis=PRIVATE)
2024-11-20T11:30:34.318 ------ [D] (Processing Status Bar Icon) ↓
[Title]: MIUI 原生通知图标
[Con

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
与 #211 归为一类问题
