### ISSUE TITLE
[WIP] 增加开关焦点通知白名单选项，方便用户可以开启一些适配了但是小米云控白名单未开启导致用不了的问题

### ISSUE THREAD

**Issue by ghhccghk** [fankes/MIUINativeNotifyIcon#223]
https://github.com/wuyou-123/FocusNotifLyric/blob/1f534c9302cc5832ef90418e3905963c418731a7/app/src/main/java/com/wuyou/notification/lyric/SystemUi.kt#L276
hook 代码可以参考这里

`

**Comment by fankes** [comment]
这个后面统一到一个模块里面，这个模块就先不改了
