### ISSUE TITLE
请求适配:皮皮虾

### ISSUE THREAD

**Issue by WuLve** [fankes/MIUINativeNotifyIcon#23]
包名:com.sup.android.superb
应用名:皮皮虾
![Screenshot_2022-02-16-21-01-17-159_com miui securitycenter](https://user-images.githubusercontent.com/48705897/154269947-a9a1995e-34aa-46e6-a348-3dd80a0df02b.jpg)
![Screenshot_2022-02-16-21-01-09-583_com miui securitycenter](https://user-images.githubusercontent.com/48705897/154269960-984754fa-cfdd-4f28-a3da-edcbc4805cda.jpg)

**Comment by naicfeng** [comment]
最好是提取图标文件发上来，不然为爱发电还需要下载各种APP，比较麻烦

**Comment by fankes** [comment]
> 最好是提取图标文件发上来，不然为爱发电还需要下载各种APP，比较麻烦

有时间就看看，后面我把提问模板搞一下，现在很多搞的都很麻烦

**Comment by fankes** [comment]
适配完毕
