### ISSUE TITLE
求适配以下App

### ISSUE THREAD

**Issue by MidNightBlackCat** [fankes/MIUINativeNotifyIcon#3]
招商银行，人民日报，即刻，MIUI天气，李跳跳
MIUI13，Android 12

![Screenshot_2022-02-05-08-16-47-559_mark via](https://user-images.githubusercontent.com/14031735/152619777-2bf56c35-7793-4b2b-ae41-29d75c2a5d50.jpg)

**Comment by fankes** [comment]
很抱歉，李跳跳无法适配，你可请其它人帮忙画图标

**Comment by fankes** [comment]
已适配完成，请更新到最新版本
