### ISSUE TITLE
[问题反馈] 不同 MIUI 版本灰度图标判断异常

### ISSUE THREAD

**Issue by sexymancheng** [fankes/MIUINativeNotifyIcon#31]
20.3.12

内测版

安卓11

1.65

图标没有被识别为彩色，而是选择做灰度处理，就白了，判断灰度图标出现问题

![Screenshot_2022-02-19-08-09-08-216_com fankes miui notify](https://user-images.githubusercontent.com/100004324/154778999-407cb277-7527-471a-9deb-c2a4a6063ce7.jpg)
![Screenshot_2022-02-19-08-09-21-696_com miui home](https://user-images.githubusercontent.com/100004324/154779008-56a03396-1977-4c98-ad37-895930354dee.jpg)

**Comment by fankes** [comment]
+ QQ浏览器 通知优化图标

**Comment by fankes** [comment]
adapt QQ阅读 通知优化图标

**Comment by fankes** [comment]
该问题已修复，若还有问题可继续 reopen 该 issues

**Comment by fankes** [comment]
该问题经过用户反馈修复失败，将继续进行定向测试

**Comment by fankes** [comment]
该问题设置为系统 BUG，无法进行修复，解决方案为尝试更新到大于 2021-5-18 之后的 MIUI 开发版
