### ISSUE TITLE
[问题与 BUG 反馈] mipush可以匹配图标，应用自己的图标出来是白块

### ISSUE THREAD

**Issue by naicfeng** [fankes/MIUINativeNotifyIcon#32]
**MIUI 版本(必填)**
13.0.4

**MIUI 版本类型(请保留一个)**

稳定版

**Android 版本(必填)**

12

**模块版本(必填)**

1.67

**使用的 Xposed 框架名称与框架版本(必填)**

lsposed

**问题的具体描述**

mipush可以匹配图标，应用自己的图标出来是白块

![Screenshot_2022-02-20-11-37-04-739_com ss android ugc aweme](https://user-images.githubusercontent.com/18218380/154827523-3895bc83-13b4-4ed8-880f-83b8ba18040c.jpg)

**Comment by fankes** [comment]
无效反馈，请提供打开模块日志后提供模块日志

**Comment by naicfeng** [comment]
确实无效，不是100%复现…

**Comment by fankes** [comment]
> 确实无效，不是100%复现…

最新版本已发布，改回了之前的方案，你可以再试试
