### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by moonbai** [fankes/MIUINativeNotifyIcon#33]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 阿里巴巴/com.alibaba.wireless/#FFFF7300

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* ![Screenshot_2022-02-21-11-46-54-452_com.coolapk.market.jpg](https://user-images.githubusercontent.com/34854875/154885900-fd7efec6-7c54-4be4-b71d-ea2a5c31a398.jpg)

购物APP

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**
安装包路径下有个类似的图标
res/drawable-xhdpi-v4/v5_bar_icon_home_sel.webp

**Comment by fankes** [comment]
请直接提供图标

**Comment by moonbai** [comment]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 主题壁纸/com.android.thememanager/#FFC15898


**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* MIUI主题APP


**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**
![Screenshot_2022-02-21-20-56-34-134_com.miui.home.png](https://user-images.githubusercontent.com/34854875/154960316-47e3309b-cb8f-4eeb-89b7-a2787eb05826.png)

**Comment by fankes** [comment]
> **需要适配的 APP 名称/包名/通知图标颜色 (必填)**
> 
> * 主题壁纸/com.android.thememanager/#FFC15898
> 
> 
> **提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**
> 
> * MIUI主题APP
> 
> 
> **提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**
> ![Screenshot_2022-02-21-20-56-34-134_com.miui.home.png](https://user-images.githubusercontent.com/34854875/154960316-47e3309b-cb8f-4eeb-89b7-a2787eb05826.png)
> 
> 
> 
> 
> 
> 

主题壁纸没有图标适配问题，请问该内容是否来自小米推送，请截图通知栏相关内容，适配图标应该填写素材而不是截屏，请重新整改否则不予立项

**Comment by fankes** [comment]
图标已适配完毕
