### ISSUE TITLE
[问题与 BUG 反馈] 单色情况下的权限管理是色块

### ISSUE THREAD

**Issue by Taylor13Swift** [fankes/MIUINativeNotifyIcon#38]
**MIUI13稳定版

**Android 版本12

* 

*1.8.5
能在 忽略彩色通知图标 关闭的条件下 对 通知图标进行优化 吗，像权限管理器，单色情况下是白色色块，如果能把 github提供的优化过的通知图标弄成单色，可能会更好

* 

**使用的 Xposed 框架名称与框架版本(必填)**

* (例如：LSPosed Zygisk/Riru 版本号)

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* (没有可空)

**问题的具体描述**

*  (复现步骤、前提以及详细截图和录屏演示)

**提供模块问题 Log 或必要 Log**

* (LSPosed 可在日志管理中查看并筛选包含 `MIUINativeNotifyIcon` 的日志)

<details><summary>展开查看</summary><pre><code>

（此处粘贴问题Log）

</code></pre></details>

**Comment by fankes** [comment]
文不对题，不能确定问题，反馈无效

**Comment by fankes** [comment]
1.该问题未遵守问题模板规则
2.忽略彩色图标功能若关闭将使用纯原生图标识别方式，涉及非单色元素的图标都会被着色为色块，遵守原生规范，在国内APP乱七八糟的生态下不可行，只是预留开关
3.原生图标具有自带的色彩功能，全部优化为单色为破坏生态，不是该模块要做的

我个人理解你的意思是要求全部图标都不要有颜色，那是不可能的。

综上，问题无效，若有其它问题请按模板规范重新提交，谢谢配合。
