### ISSUE TITLE
求适配高德地图

### ISSUE THREAD

**Issue by MidNightBlackCat** [fankes/MIUINativeNotifyIcon#4]
求适配高德地图
MIUI13，Android 12

![Screenshot_2022-02-05-08-27-43-516_com coolapk market](https://user-images.githubusercontent.com/14031735/152620448-28732c96-0ac4-4c3e-841d-d1a8a8f78e52.jpg)

**Comment by fankes** [comment]
已适配完成，请更新到最新版本
