### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by troublewind** [fankes/MIUINativeNotifyIcon#40]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 朴朴/com.pupumall.customer/#25C867

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**
*  买菜app
![image](https://user-images.githubusercontent.com/16570023/156342365-34888f19-c889-4b65-af8d-2abfc46cb511.png)

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**
![image](https://user-images.githubusercontent.com/16570023/156341649-c9c63aaa-308d-4df9-99ec-8f5e35f5675b.png)

**Comment by fankes** [comment]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/37344460/156436524-1ca499f1-8734-4475-8f72-0e621a7242fa.png">
由于你提供的图标有问题自带叠加层，已重新画了一个，下次请规范提交否则不再处理这类问题
