### ISSUE TITLE
替换图标场景

### ISSUE THREAD

**Issue by MartinVon1021** [fankes/MIUINativeNotifyIcon#42]
目前只替换了状态栏和通知部分，是否可以替换不重要通知右侧的图标？以及息屏通知中的图标？

**Comment by MartinVon1021** [comment]
![IMG_20220306_150510](https://user-images.githubusercontent.com/23263857/156912866-bdd22158-cd0e-4f8f-86e4-eb0710a5000d.jpg)
如图，右边的图标都没有替换

**Comment by fankes** [comment]
该问题已有相同立案
