### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by tobywong0529** [fankes/MIUINativeNotifyIcon#43]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* (与你/com.uneed.yuni)

* 

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* ![Screenshot_2022-03-07-16-07-07-154_com coolapk market](https://user-images.githubusercontent.com/79052768/156992029-26f73dc0-66c7-4687-95ed-516135653bef.jpg)
聊天软件

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)
* 之前提交的代码
*   {
    "appName": "与你",
    "packageName": "com.uneed.yuni",
    "iconBitmap": "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAADGWlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjaY2BgnuDo4uTKJMDAUFBUUuQe5BgZERmlwH6egY2BmYGBgYGBITG5uMAxIMCHgYGBIS8/L5UBA3y7xsDIwMDAcFnX0cXJlYE0wJpcUFTCwMBwgIGBwSgltTiZgYHhCwMDQ3p5SUEJAwNjDAMDg0hSdkEJAwNjAQMDg0h2SJAzAwNjCwMDE09JakUJAwMDg3N+QWVRZnpGiYKhpaWlgmNKflKqQnBlcUlqbrGCZ15yflFBflFiSWoKAwMD1A4GBgYGXpf8EgX3xMw8BUNTVQYqg4jIKAX08EGIIUByaVEZhMXIwMDAIMCgxeDHUMmwiuEBozRjFOM8xqdMhkwNTJeYNZgbme+y2LDMY2VmzWa9yubEtoldhX0mhwBHJycrZzMXM1cbNzf3RB4pnqW8xryH+IL5nvFXCwgJrBZ0E3wk1CisKHxYJF2UV3SrWJw4p/hWiRRJYcmjUhXSutJPZObIhsoJyp2V71HwUeRVvKA0RTlKRUnltepWtUZ1Pw1Zjbea+7QmaqfqWOsK6b7SO6I/36DGMMrI0ljS+LfJPdPDZivM+y0qLBOtfKwtbFRtRexY7L7aP3e47XjB6ZjzXpetruvdVrov9VjkudBrgfdCn8W+y/xW+a8P2Bq4N+hY8PmQW6HPwr5EMEUKRilFG8e4xUbF5cW3JMxO3Jx0Nvl5KlOaXLpNRlRmVdas7D059/KY8tULfAqLi2YXHy55WyZR7lJRWDmv6mz131q9uvj6SQ3HGn83G7Skt85ru94h2Ond1d59uJehz76/bsK+if8nO05pnXpiOu+M4JmzZj2aozW3ZN6+BVwLwxYtXvxxqcOyCcsfrjRe1br65lrddU3rb2402NSx+cFWq21Tt3/Y6btr1R6Oven7jh9QP9h56PURv6Obj4ufqD355LT3mS3nZM+3X/h0Ke7yqasW15bdEL3ZeuvrnfS7N+/7PDjwyPTx6qeKz2a+EHzZ9Zr5Td3bn+9LP3z6VPD53de8b+9+5P/88Lv4z7d/Vf//AwAqvx2K829RWwAAAK5QTFRFAAAAcnJyc3NzdHR0enp6enp6ampqZ2dnZGRkYWFhYGBgW1tbWlpaV1dXVlZWVVVVsLCwr6+vtra2t7e3vLy8vr6+vr6+wMDAxMTExMTExcXF0NDQ0dHR09PT19fX29vb3Nzc4ODg5eXl5eXl5eXl5ubm5+fn6+vr7e3tycnJx8fHxMTEtLS0tLS0pKSkoKCgmpqamZmZlJSUkJCQjY2NjIyMVVVVVlZWr6+vsLCwivOwzgAAADZ0Uk5TAKOjn5WTtbvBy8vZ3d/f37GxlZGBenh2aGZiRkY+NCooHBYUEhIQBgIgIiY4PFBUYGBocHJ0OmMjUgAAAQ5JREFUeNrNkNlSwzAMRW/ZyyKpQFnD3gBhTVjs5v9/DKm2w9TJB/TYM364R9czwipRBK4wyONUpJ23isgF+jxLq/FcDUWm6HFiUYfcIEdUWMwH8awvxNHj4vqhLGclMi4ni1G5xzClhPkZ0OyxQnZ/KySexP6f3KFi9t7pdV4PvSFxaxVHALuEN4P/O2wNBWp2aT4wQmKiDQU2NQo3PoTEuZgw9rHBxRJCx6GosBvDzuAKHadiQopS1T6WGHufyvmAXFZhgqWoiL17BVu+kTVY8SdQN5VqJmCZHfuAvqG8O4My4cuZwby9TuysLW944W6HQa2RsUbR8PbSFnr8sJaERTOPMMRH09RNbWCF+AO12UdjTNJjAAAAAABJRU5ErkJggg==",
    "contributorName": "TOBY",
    "isEnabled": true,
    "isEnabledAll": false
  }

**Comment by fankes** [comment]
已添加
