### ISSUE TITLE
[问题与 BUG 反馈] 通知图标在白色背景下没有使用纯黑色

### ISSUE THREAD

**Issue by YifePlayte** [fankes/MIUINativeNotifyIcon#44]
**MIUI 版本**

* MIUI13 22.3.3

**MIUI 版本类型**

* 内测版

**Android 版本**

* A12

**模块版本**

* 1.95

**使用的 Xposed 框架名称与框架版本**

* LSPosed Zygisk 1.7.2(6379)

**问题的具体描述**

*  白色背景下，微微触发全面屏手势，能很明显得看到通知图标用的不是纯黑色，与状态栏其他元素不和谐。
![IMG_20220312_154618](https://user-images.githubusercontent.com/62252171/158009213-bc1f0bb3-1458-4db0-8958-a8880a7e8a38.jpg)

**提供模块问题 Log 或必要 Log**

* 个人认为此bug不需要提供log

**Comment by fankes** [comment]
状态栏图标的颜色取自系统默认着色，若存在问题则是 MIUI 自身问题，模块无义务负责修复，故此该 bug 非模块问题，不成立。

**Comment by fankes** [comment]
闲的没事干把这个 BUG 修了，MIUI 下次也不要再教我做事了，最新版本请查收
