### ISSUE TITLE
[问题与 BUG 反馈] 模块会破坏MIUI的图标动态显示个数机制

### ISSUE THREAD

**Issue by scrpr** [fankes/MIUINativeNotifyIcon#45]
**MIUI 版本**

* MIUI13 22.3.21

**MIUI 版本类型**

* 内测版

**Android 版本(必填)**

* Android 12

**模块版本(必填)**

* 2.16

**使用的 Xposed 框架名称与框架版本(必填)**

* LSPosed Zygisk 1.7.2 (6379)

**问题的具体描述**

*  先前模块修复了开发版只能显示一个通知图标的问题，而这个问题在22.3.21上已修复
* 但是模块似乎依然在生效，这带来了一些问题：
* 见下方对比，在右侧图标太长时，MIUI会动态地减少通知图标的显示个数，使其不会与右侧重叠，而模块破坏了这种行为
* 建议在22.3.21及以上版本禁用模块的workaround

https://user-images.githubusercontent.com/46473171/159520056-0ff18f99-bc03-4961-b565-85ae7e01079e.mp4

https://user-images.githubusercontent.com/46473171/159520097-c70f35d5-4f1c-4b4f-98c3-58f77c7e353d.mp4

**提供模块问题 Log 或必要 Log**

* 不需要log

**Comment by fankes** [comment]
应该与这个无关，你可以把解除通知图标个数的功能关掉，再试试

**Comment by scrpr** [comment]
> 应该与这个无关，你可以把解除通知图标个数的功能关掉，再试试

没有效果，只有在开关模块后才会体现出区别

![Screenshot_2022-03-23-01-51-40-228-edit_com fankes miui notify](https://user-images.githubusercontent.com/46473171/159544438-41a70253-2e48-409c-9331-c345008de0b8.jpg)
![Screenshot_2022-03-23-01-50-49-591-edit_com fankes miui notify](https://user-images.githubusercontent.com/46473171/159544485-27ad8661-7f24-4a90-91ef-ee4b6696e690.jpg)

**Comment by fankes** [comment]
已经加上那几个出问题的版本了，后面整合完毕后再发 release

**Comment by scrpr** [comment]
尝试编译了最新commit，问题已解决

**Comment by fankes** [comment]
最新版本的动态图标功能尚在测试阶段，不保证会出现bug，后期请及时更新到最新release版本

**Comment by fankes** [comment]
重新commit了一下，昨天晚上修了一个bug出来
