### ISSUE TITLE
能否增加关闭某个应用的图标

### ISSUE THREAD

**Issue by smyhm** [fankes/MIUINativeNotifyIcon#48]
**MIUI 版本(必填)**

* miui13

**MIUI 版本类型(请保留一个)**

* 公测版

**Android 版本(必填)**

* 11

**模块版本(必填)**

* 2.2

**使用的 Xposed 框架名称与框架版本(必填)**

* LSPosed Zygisk  1.8.0

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* (没有可空)

**问题的具体描述**

*  能否增加关闭某个应用的通知图标功能，或者用小的空白图标来替换（最好不留空），有些调度软件会常驻通知栏，关闭通知的话会造成一些麻烦（比如看不到调度信息，或者自动休眠），常驻图标无论怎么设置重要性都会显示在状态栏。
* 
![WechatIMG1306](https://user-images.githubusercontent.com/101782263/160577222-aa3b66ab-4606-44e2-833f-83d626a769b9.jpeg)
![WechatIMG1305](https://user-images.githubusercontent.com/101782263/160577263-a35d5f34-9e03-42d2-92fc-963591a86435.jpeg)

**提供模块问题 Log 或必要 Log**

* (LSPosed 可在日志管理中查看并筛选包含 `MIUINativeNotifyIcon` 的日志)

<details><summary>展开查看</summary><pre><code>

（此处粘贴问题Log）

</code></pre></details>

**Comment by smyhm** [comment]
好吧  标签是bug  我不会改

**Comment by fankes** [comment]
可从 #18 找到处理不重要折叠通知的模块，由于 MIUI 删除这个系统设置破坏了原生生态，无法处理这个问题，这不是模块要做的事情。
