### ISSUE TITLE
[问题与 BUG 反馈] *壁纸取色与系统自定义强调色不统一*

### ISSUE THREAD

**Issue by HZYint** [fankes/MIUINativeNotifyIcon#49]
**MIUI 13**

* 

* 稳定版

**Android 12**

* 

**模块版本2.3**

* 

**LSPosed Zygisk1.8.0**

* 

**壁纸取色与系统自定义强调色不统一
![Screenshot_2022-03-30-14-12-23-848_com miui notification](https://user-images.githubusercontent.com/79033942/160765535-b3803b65-1f3e-4232-9213-dc2ccf85ec03.jpg)
原因可能与新增壁纸取色有关
**

*  (复现步骤、前提以及详细截图和录屏演示)

**提供模块问题 Log 或必要 Log**

**Comment by fankes** [comment]
图标的颜色遵循的是 Android 12 的默认壁纸取色，该项无法做出调整，文字的颜色是 MIUI 主题设置的，默认的主题的颜色是跟随系统的，所以不是 BUG，若要颜色统一请更换你当前使用的主题
