### ISSUE TITLE
能否给应用名称着色呢

### ISSUE THREAD

**Issue by Sontrol** [fankes/MIUINativeNotifyIcon#50]
既然图标已经有背景色那是否可以给应用名称也着色呢。。
![Screenshot_2022-03-31-16-46-47-168_com android browser](https://user-images.githubusercontent.com/53102099/161015599-d287a26d-21b0-450e-a517-004cf6b2f4b0.jpg)

>

**Comment by fankes** [comment]
应用名称着色非原生规范
