### ISSUE TITLE
[通知图标优化适配反馈]快手极速版

### ISSUE THREAD

**Issue by Mc-user1688** [fankes/MIUINativeNotifyIcon#53]
快手极速版/com.kuaishou.nebula
![Screenshot_2022-04-05-18-20-04-778_com miui home](https://user-images.githubusercontent.com/73388367/161733531-3ce946c8-bf79-40a6-ae40-e26918ed0ef0.png)
下载渠道：小米应用商店
![Screenshot_2022-04-05-18-21-36-233_com xiaomi market](https://user-images.githubusercontent.com/73388367/161733708-22bdccdb-8495-45ef-a9c5-604719ac3142.png)

**Comment by fankes** [comment]
由于图标一样不需要再画了，使用 `快手` 图标与之。
