### ISSUE TITLE
English Translation request

### ISSUE THREAD

**Issue by furopi** [fankes/MIUINativeNotifyIcon#54]
Great app, I wish there would be an english translation available!

Kind regards fromm Germany 😄
Keep up the good work! ❤️

**Comment by fankes** [comment]
This software is mainly used by people in China.

This request mabe a feature in future.

They need to be determined by the number of people needed.

Thank you for your request.

**Comment by nyakze** [comment]
I would also like to request localization support. This module is very useful, but I had to use text recognition software to understand what each option meant. If localization support was added, I'd gladly contribute and help to translate the app into English and Russian.

**Comment by fankes** [comment]
> I would also like to request localization support. This module is very useful, but I had to use text recognition software to understand what each option meant. If localization support was added, I'd gladly contribute and help to translate the app into English and Russian.

Yes it is, but this module is only for Chinese people and the online rules is same. So, mabe a future do this when people need it. Thank you.
