### ISSUE TITLE
关于图标着色

### ISSUE THREAD

**Issue by moonbai** [fankes/MIUINativeNotifyIcon#55]
我有一个bug朋友想让我问一下能不能加个通知页icon不着色的功能，就类似下边这种灰色的，他比较喜欢😄
![Screenshot_2022-04-12-16-35-10-599_com.fankes.notifyicondebugging.jpg](https://user-images.githubusercontent.com/34854875/162918821-a5d70246-0a25-42d4-9632-c92404038634.jpg)

**Comment by fankes** [comment]
着色是原生规范，想改请fork模块自己修改，我不会改的，这不是这个模块该做的事情
