### ISSUE TITLE
美团部分图标替换失败

### ISSUE THREAD

**Issue by mahoshojoHCG** [fankes/MIUINativeNotifyIcon#56]
**MIUI 版本(必填)**

* 13.0.28

**MIUI 版本类型(请保留一个)**

* 稳定版（eu版）

**Android 版本(必填)**

* 12

**模块版本(必填)**

*  2.5

**使用的 Xposed 框架名称与框架版本(必填)**

* LSPosed Zygisk  1.8.2

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* 强制使用MIUI手势（我的模块）

**问题的具体描述**

*  (复现步骤、前提以及详细截图和录屏演示)
美团部分模块未能成功替换

![Screenshot_2022-04-19-19-03-05-061_app lawnchair](https://user-images.githubusercontent.com/21016506/163990181-473b6881-1606-4d4b-908b-823f85bb3515.jpg)

![Screenshot_2022-04-19-19-00-44-093_app lawnchair](https://user-images.githubusercontent.com/21016506/163990125-b2c6e4c7-c803-4d3b-9c4f-1c6673138e62.jpg)

**提供模块问题 Log 或必要 Log**

* (LSPosed 可在日志管理中查看并筛选包含 `MIUINativeNotifyIcon` 的日志)
 （无错误log）

**Comment by fankes** [comment]
APP 不规范问题，请开启强制替换，云端规则将更新此问题
