### ISSUE TITLE
[问题与 BUG 反馈] *简要描述问题原因*

### ISSUE THREAD

**Issue by langkiss** [fankes/MIUINativeNotifyIcon#57]
**MIUI 版本(必填)**

* 13.0.1.0

**MIUI 版本类型(请保留一个)**

* 稳定版

**Android 版本(必填)**

* 11

**模块版本(必填)**

* 2.5

**使用的 Xposed 框架名称与框架版本(必填)**

* LSPosed Zygisk 1.8.3

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* chimi，customizer

**问题的具体描述**

*  锁屏后卡死，极大概率，一般锁屏10分钟后或者有新通知出现后再次唤醒会复现，进入系统后显示系统界面崩溃，关闭其他两个使用系统界面的模块后复现，关闭此模块后不复现。打开此模块开关关闭其他选项后仍复现。

**提供模块问题 Log 或必要 Log**

* (LSPosed 可在日志管理中查看并筛选包含 `MIUINativeNotifyIcon` 的日志)

<details><summary>展开查看</summary><pre><code>

（此处粘贴问题Log）

</code></pre></details>

**Comment by fankes** [comment]
No log
