### ISSUE TITLE
[问题与 BUG 反馈] 通知栏一段时间后会"消失"

### ISSUE THREAD

**Issue by naicfeng** [fankes/MIUINativeNotifyIcon#58]
**MIUI 版本(必填)**

*13

**MIUI 版本类型(请保留一个)**

稳定版

**Android 版本(必填)**

12

**模块版本(必填)**

2.5

**使用的 Xposed 框架名称与框架版本(必填)**

LSPosed Zygisk 1.8.3

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* (没有可空)

**问题的具体描述**

状态栏刷新逻辑问题，偶发状态栏消失，几秒后恢复。
是否在后台刷新状态栏，效率太低导致的？

**Comment by fankes** [comment]
要求复现测试和录屏，请在一天内完成，否则该问题将不成立

**Comment by fankes** [comment]
由于您长时间未回复，该问题将被设置为无效处理。
