### ISSUE TITLE
请求图标适配反馈

### ISSUE THREAD

**Issue by lzx23333** [fankes/MIUINativeNotifyIcon#6]
1.拼多多 com.xunmeng.pinduoduo
2.京喜 com.jd.pingou
3.掌上英雄联盟 com.tencent.qt.qtl
4.央视频 com.cctv.yangshipin.app.androidp
5.百度网盘 com.baidu.netdisk
6.京东极速版 com.jd.jdlite
7.爱奇艺 com.qiyi.video
8.中国建设银行 com.chinamworld.main
![Screenshot_2022-02-06-10-36-23-595_com miui home jpg](https://user-images.githubusercontent.com/71322249/152665869-3c9e68fb-f405-4e6f-871c-725e932505f4.png)
![Screenshot_2022-02-06-10-36-34-455_com miui home jpg](https://user-images.githubusercontent.com/71322249/152665874-4e4950c8-af3b-40c5-b397-ee2ae5325516.png)
![Uploading Screenshot_2022-02-06-10-36-08-229_com.miui.home.jpg.png…]()
![Uploading Screenshot_2022-02-06-10-12-28-344_com.miui.home.jpg.png…]()

**Comment by fankes** [comment]
1.3 版本已添加，更新即可
