### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by 15354079449** [fankes/MIUINativeNotifyIcon#67]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 名称:Surf VPN    包名:	com.xfx.surfvpn
![com.xfx.surfvpn.png](https://user-images.githubusercontent.com/96981074/173217572-a426182c-136e-4b5e-b85a-3ca1c90f65f0.png)（图标颜色）

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* ![Screenshot_2022-06-12-13-56-10-416_com.android.vending.png](https://user-images.githubusercontent.com/96981074/173217933-a37463ac-d3ff-4678-b494-f00e617be037.png)
用途:上网

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

**Comment by fankes** [comment]
不会适配敏感性质的应用
