### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by bk227918** [fankes/MIUINativeNotifyIcon#68]
![ic_launcher_foreground](https://user-images.githubusercontent.com/63150136/174667539-23c3dac3-4801-43ed-b573-8eb2e7ec2f01.png)
请求适配
应用名称:1TS+
应用包名:com.unexpected.ts

**Comment by fankes** [comment]
破坏模板提交的 `issues` 将直接被关闭
