### ISSUE TITLE
不存在Ramdisk版本的LSPosed

### ISSUE THREAD

**Issue by Howard20181** [fankes/MIUINativeNotifyIcon#7]
是Riru
Riru已经停更，现在开发建议基于Zygisk版本的进行测试
且在Zygisk上并没有问题，可以把那个建议使用Riru去掉了 
还有LSPosed前面三个字母是大写的 
Readme 和应用中的FAQ需要改改

**Comment by fankes** [comment]
那可能是MIUI13最新开发版有问题，根据用户反馈来的，后期再修改

**Comment by fankes** [comment]
本来是想写Ramdisk版本的Magisk使用的Riru的

**Comment by fankes** [comment]
详见酷友问题反馈回复层
![Screenshot_2022-02-07-14-34-50-414_com.coolapk.market.jpg](https://user-images.githubusercontent.com/37344460/152736990-a9bbda72-ef24-4c9f-982a-00171ccf33b9.jpg)

**Comment by Howard20181** [comment]
> 本来是想写Ramdisk版本的Magisk使用的Riru的

Ramdisk状态对LSPosed没有影响，对于这种反馈建议问清楚LSPosed版本，可能是旧版本bug

**Comment by fankes** [comment]
> > 本来是想写Ramdisk版本的Magisk使用的Riru的
> 
> Ramdisk状态对LSPosed没有影响，对于这种反馈建议问清楚LSPosed版本，可能是旧版本bug

雀食，后面改一下

**Comment by fankes** [comment]
文案已修正
