### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by Matt0o0** [fankes/MIUINativeNotifyIcon#76]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 美团开店宝/com.sankuai.meituan.merchant/#FBDD35

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**
![Screenshot_2022-06-24-21-00-46-127-edit_com xiaomi market](https://user-images.githubusercontent.com/44046317/175541227-051684d1-e020-4db8-bb4c-c19d4621b0f0.jpg)

美团大众点评店铺用，常驻通知栏，就这一个图标是黄色，很碍眼，希望能匹配成黑白跟其他图标统一，万分感谢！

* 

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

**Comment by fankes** [comment]
+内容中心(MIUI)

**Comment by fankes** [comment]
done
