### ISSUE TITLE
原神图标适配修改

### ISSUE THREAD

**Issue by YifePlayte** [fankes/MIUINativeNotifyIcon#8]
![Screenshot_2022-02-08-11-04-12-889_com miui securitycenter](https://user-images.githubusercontent.com/62252171/152910341-9ce28315-a192-4e56-9ce0-acdffe2972ed.jpg)
原神拥有下面这张其自带的通知图标（提取自安装包，位置为res/drawable/jpush_notification_icon.png，从文件名推测用于jpush），希望将原神通知图标修改成此图标。
![jpush_notification_icon](https://user-images.githubusercontent.com/62252171/152910397-8fb8605c-6b62-446d-b72d-f89c8f4994f7.png)

**Comment by YifePlayte** [comment]
这个issue尾部是有一张图的。。
![IMG_20220208_191848](https://user-images.githubusercontent.com/62252171/152976939-c548504a-fbdc-4c66-b682-3903b787cccc.jpg)

**Comment by fankes** [comment]
> 

我看到了

**Comment by fankes** [comment]
1.36 fixed.
