### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by arieschao-1** [fankes/MIUINativeNotifyIcon#80]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 不背单词/cn.com.langeasy.LangEasyLexis

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 下载渠道：各大应用商店，我是从酷安下载的
* 下载渠道截图：
![image](https://user-images.githubusercontent.com/45620017/176982191-022d0cc8-5472-4286-a262-149d5db5d75a.png)
* 用途：背记单词

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

![0](https://user-images.githubusercontent.com/45620017/176982882-7c9ed720-5126-4d92-8e25-014a88dfb42a.png)
![1](https://user-images.githubusercontent.com/45620017/176982891-a9e74780-3ed2-4004-8181-d8f2c718cf61.png)
![2](https://user-images.githubusercontent.com/45620017/176982898-c8601a7c-f9a1-4af8-a1e2-78744f9980a8.png)
![3](https://user-images.githubusercontent.com/45620017/176983017-40c27d16-7547-4d98-ac9a-7be88d889e86.png)
![4](https://user-images.githubusercontent.com/45620017/176983021-61b534b8-3161-4fe2-8487-4978101a48f3.png)
![5](https://user-images.githubusercontent.com/45620017/176983022-a42a41ea-5e1d-4891-b0ab-84f35ea4ae1e.png)

**Comment by fankes** [comment]
done
