### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by xy1100** [fankes/MIUINativeNotifyIcon#83]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 小宇宙/app.podcast.cosmos/#50B7DA

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

*![Screenshot_2022-07-14-07-51-11-121_com xiaomi market](https://user-images.githubusercontent.com/9368244/178856029-e368be1d-6f07-46dd-ba53-758903565539.jpg)

* 小米应用商店下载，播客APP

**Comment by fankes** [comment]
+驾考宝典

**Comment by fankes** [comment]
done
