### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by wuhang2003** [fankes/MIUINativeNotifyIcon#84]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 原神·B站渠道服/com.miHoYo.ys.bilibili/#0

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 
![Screenshot_2022-07-18-19-11-15-899_tv danmaku bili](https://user-images.githubusercontent.com/108316419/179499384-b2305800-9d2e-42df-a7d3-8bab499ff917.jpg)

* B站游戏中心即可下载

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* 已有不同包名但相同应用的图标，只需改规则里的包名即可套用

**Comment by fankes** [comment]
那你 PR

**Comment by fankes** [comment]
@HeMing505

**Comment by HeMing505** [comment]
搞定
