### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by wuhang2003** [fankes/MIUINativeNotifyIcon#86]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 菠萝包轻小说/com.sfacg/#0

* 刺猬猫阅读/com.kuangxiangciweimao.novel/#FFC23D

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 刺猬猫阅读：https://www.coolapk.com/apk/com.kuangxiangciweimao.novel

* 菠萝包轻小说：https://www.coolapk.com/apk/com.sfacg
（对于菠萝包轻小说，最新版本可能无法在 Root 环境下使用。[提供一个老版本下载地址以方便适配](https://wwb.lanzouw.com/iXLJV076qtsh)，密码 d1su）

* 以上二者皆是小说客户端

**Comment by fankes** [comment]
done
