### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by fankes** [fankes/MIUINativeNotifyIcon#89]
![Screenshot_2022-07-25-05-47-33-205_com.coolapk.market-edit.jpg](https://user-images.githubusercontent.com/37344460/180667142-f1ea8de0-b0fa-46f3-846e-af88b4edea4b.jpg)

**Comment by fankes** [comment]
请求适配图标：喵喵折 com.henzanapp.miaomiaozhe 

https://www.coolapk.com/apk/com.henzanapp.miaomiaozhe

**Comment by NekoMua** [comment]
iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAFMklEQVRoge2Za4hWRRjHf+u67qaVFmurIa2kqaVuZd6iC0E3Kq0MtsgyguqDQfkhIqUP0hdrLYhKw5JYWikK7WJRlNEmaaVdTCtJqLVMLCqt1bWtNXf/MfhszZ7mXN59z14++IcD531n5pnnP8/MPJfDUfQzlPjqSOot7a4HPgJ2FyOkpOQ/9QfkoVU3sBBYD9ycl8C+IDIEOAk4FVgFvAOcXqzQviBSCQz3fl8CfAosAkq7K7QQItOBZ4DB3Z3MMAwYFPnPyVwCvA2ML1L+kcMe81RI2qoj2CCpMqFv0jNU0hIlY5+kG7PI6w6RhyNTb5E0JsNkoyXNlvSQpEZJP6WQ8FEnqSRPIlMkHQ5MtEfSVK/fIEnjJM2TVG8WbC1A8RBekjQkC5E0P+LaG4GLYrjvA5YDY4EZQDUwMHUPF4aNwDXAb/9TzvMjaUTmAC/nrFh38D4wC2jpDpFjgG3Aaf2AiMMG4Argj84/snr26/oRCYcLgCfjGuOIOKoLek6nWLQChxPabwHuCDXEba3zzZS9ge+Ap4F1wK/mHKcAtwKXBeY/AJwJfO9vrS7wrrb6Iq/NrHhV0gkJvuKeGDlPZfEjzms39wIJFyEMDChfLWmW93thYOx+SVW+7qEzcjEwtIAttR1YCTwKrAA+yzCmw0J5dx5GAM95EfBjFlh2YqnN4eP4BN/2r0VWZlzRHRZ+lAZWdaak9Qljt3l93fhaSZ9LWiNpl22pYV6fRQEZj/i6Ry3iotILM6zoZuv3OtAeaN9kB/X5mPFfeu9u/DR7dx58i0UHbV6fbwIyRiURGQmMTiHRDNQCv1iS5OcQTvkH7f0QcBuwIyAjesU2AHOBN4GvbEGneu2hk90ld4kSmRDIFaJY4eXaVwOfADVABeDM/a7X/y/LM6KIZoRnmdzJ5r3bbKE6MSogI7QTjLZ0b8q56JA0I3Ie5lskvEnSbkkPSBrrtVdJaonIOSRpvNfnOHvmSnolcOY2BnSpS7LIuBRr/B7Zry7qvclWcJoVFJzD2uv1ce97InLKIpZqsec9yxJ9uC13XkCXdUkWWZNikZ9t5TpX6ljLV06WtFnSnZLuljTH6zNA0vYYeUutPc4hXi7pQGDcty5rTSKyOoWIS7AmRyZ7wq5Tt32aJC2XdKnX7tLbvQky3ba5yq5bdxWXS5okaVlMQudwe5pnfzGFiMMCT8kSyxInSlpsPii6qldmkCmz9teSdkpqT+jX2BkRJBGpyzBhU0z6OV3SqsD/SY6xUDhnOSJLzl6bUfALMXu7IvJ7cY4k3M1Yk7X4MCZhX0axNqGSMtzOTl74QtKEQooPpRZ+nBNPtwvclfmGhSQHgXLgbGA2UJVRRhoaLMlrjvZLy0fuynEli0FTWqEuySJYhra1D/P1/RbqLAtZwUeWKspM87LxTid/7ATqgWezfjfJkupiZm3r4e3jvPZrNtfgpG1UbKXRxTiPWzEgD7gJdgEfAmuBDwJxWGZktUjnU24x1McpHjeEaP92K4gXtPJ5WCSKiWadGvuOMdJLcNoth/jRcmwX4d4fk//Pt/yjKBRS+y0GbvucGzPeHewzIulsweiNj6ENCSSwykl1nhP2BJFrgXkpfTosKcsNeRMpj8nRoyjL5Vuhh7yJ3JDxU3OZVddzQ55ESuIq5QG4eSeZBXNBnkTKrZqe5Sb60xxjjEcrHHl+73M1rPuMjCvUnWhbaID5mL+tn6uqvGVxVVHXr4+e8CPOMqdY9FxpBb9W+2R20Czxg1Uii1M+LkQ5ir4G8A9mHYkeHsU7cgAAAABJRU5ErkJggg==

![com henzanapp miaomiaozhe](https://user-images.githubusercontent.com/59407295/180780725-f2185295-b877-4f81-ac65-46b3edf84512.png)
背景颜色#ffff2a3c

**Comment by NekoMua** [comment]
随性做的，不知道好不好

**Comment by NekoMua** [comment]
![com henzanapp miaomiaozhe](https://user-images.githubusercontent.com/59407295/180786470-a5c224bd-3a7f-447b-9b33-d787dbbc8646.png)
颜色#ffff2a3c

**Comment by NekoMua** [comment]
随性做的图标。不知道好不好
