### ISSUE TITLE
图标适配反馈

### ISSUE THREAD

**Issue by YifePlayte** [fankes/MIUINativeNotifyIcon#9]
![IMG_20220208_130326](https://user-images.githubusercontent.com/62252171/152921580-3525d441-91aa-4169-9c88-0e7dc334dbd2.jpg)
钉钉 com.alibaba.android.rimet
![notification_statusbar_icon](https://user-images.githubusercontent.com/62252171/152921515-912669cf-e3b8-480e-a198-5a2d242801d2.png)
上面是钉钉安装包里提取的通知图标，路径为res/drawable/notification_statusbar_icon.png，但不知为何没有被使用。

**Comment by fankes** [comment]
大多数可能是mipush的问题，应用自身应该是正常的

**Comment by fankes** [comment]
1.36 fixed.
