### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by lesssugar6** [fankes/MIUINativeNotifyIcon#94]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 美丽修行/cn.bevol.p/

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 酷安下载，用途为化妆品护肤品成分查询

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* 

*

**Comment by fankes** [comment]
缺少必要项目，适配请求无效
