### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by hmy65** [fankes/MIUINativeNotifyIcon#95]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

*zaker新闻

* 

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* https://play.google.com/store/apps/details?id=com.myzaker.ZAKER_Phone&hl=en&gl=US

  相对好用的第三方新闻客户端。

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

https://play-lh.googleusercontent.com/3zCPCBRrJFIEsDPhNst4-dLROwHYzIbmCOzK_I2W7xeLqCqR2HFiCkVFrulwNSIGHC-H=w240-h480-rw

**Comment by fankes** [comment]
@NeoMua
