### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by zxygood** [fankes/MIUINativeNotifyIcon#97]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* (示例：小米音乐/com.miui.player/#fff16033)

* 三国志幻想大陆/com.ali.games.star.mini01
![三国志幻想大陆](https://user-images.githubusercontent.com/108561839/183282325-b384e556-3d65-4fda-bfbd-9e1fac53c58a.png)

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by fankes** [comment]
@NekoMua

**Comment by NekoMua** [comment]
> * 三国志幻想大陆

这游戏图标我都不知道咋扣😓😓

**Comment by NekoMua** [comment]
> @NekoMua

老哥你来吧，游戏图标我蚌埠住了🤔🤔

**Comment by fankes** [comment]
@NekoMua 随便找个图标就行了 iconfont.cn
