### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by fffzzzyyy2333** [fankes/MIUINativeNotifyIcon#99]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* (求适配)

* Chrome(com.android.chrome)

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 谷歌商店

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (无素材)

* (暂无素材)

**Comment by fankes** [comment]
你在开玩笑吧这APP没有图标规范，申请无效，请补充确实存在的场景问题再提交，谢谢
